eclipse/che-che4z-lsp-for-cobol

com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/model/CopybookStorable.java

Making a public constant just final as opposed to static final leads to duplicating its value for every instance of the class, uselessly increasing the amount of memory required to execute the application.

Make final field static too to fix technical debt

---

com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/completions/Completions.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java

Log the exceptions that appear within the asynchronous operations in MyTextDocumentService in order to increase code maintainability. Now all the requests will be logged with aa message and the exception's stack trace.

Add uncaught exception handling for async operations #78

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/internal-changes.md

Provide issue templates in order to simplify bug reporting and feature requests for the users.

Provide issue templates

---

com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/impl/CobolPreprocessorImpl.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/transformer/CobolLinesTransformation.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/transformer/ContinuationLineTransformation.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/preprocessor/sub/line/transformer/ContinuationLineTransformationTest.java

Another one step to finalize dependency injection for language engine.

Make ContinuationLineTransformation stateless to simplify DI #24

---

com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngine.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/parser/listener/VerboseListener.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/CobolPreprocessor.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/impl/CobolPreprocessorImpl.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/cleaner/CobolDocumentCleaner.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/cleaner/impl/CobolDocumentCleanerImpl.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/AnalyseCopybookTask.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/CopybookAnalysis.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/CopybookParallelAnalysis.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/CobolSemanticParser.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/CobolSemanticParserImpl.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/CobolSemanticParserListenerImpl.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngineTest.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/semantics/CobolCleanExtraLanguageTest.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/semantics/CobolVariableCheckTest.java
com.ca.lsp.cobol/lsp-core-domain/src/main/java/com/broadcom/lsp/domain/cobol/event/model/RequiredCopybookEvent.java
com.ca.lsp.cobol/lsp-core-domain/src/test/java/com/broadcom/lsp/domain/cobol/event/CopybookEventsTest.java
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/references/SemanticElementOccurrences.java
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/validations/LanguageEngineFacade.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/HighlightsTest.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/completions/CompletionsChainTest.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/validations/UseCaseUtils.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/AnalyzeCopybookCaching.java

The currently processing document URI is provided to the language engine to keep the document positions filled-in properly. 
Also, it is useful to build a dependency graph.

Provide the document URI for the language engine

---

clients/cobol-lsp-vscode-extension/src/extension.ts

Update correct information about language ID when calling LanguageClient constructor in order to have everything aligned "on the same page".

Update extension.ts with correct language ID

---

com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/document/impl/CobolSemanticParserImpl.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/semantics/CobolVariableContext.java
com.ca.lsp.cobol/lsp-core-cobol-parser/src/test/java/com/ca/lsp/core/cobol/semantics/CobolVariableContextTest.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/AllTests.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestMissingCopybookNotInVariableList.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/UseCaseSuite.java

In the current solution, there are copybook marks that are used to build the variable structure using copybooks. The scenario when the copybook is missing and the structure cannot be built was not covered and the mark was not removed.
Now variable semantic context has the capability to remove these marks on demand.

Remove copybook name from the variable list if copybook is missing GH-186

---

com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java

Add logic to ignore '*.cpy' files in didChange handler.
Change didOpen logic. Call registerDocument for register only processed documents.

Copybook extension check fails

---

CHANGELOG.md
clients/cobol-lsp-vscode-extension/CHANGELOG.md
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/communications/ServerCommunications.java
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/utils/FileSystemUtils.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/utils/FileSystemUtilsTest.java

Fix #225 allowing the user to have a decoded URI message info on the ```Communication``` class

225 no escape chars in filename

---

clients/cobol-lsp-vscode-extension/src/CopybooksDownloader.ts

The method was invoked as ```this.listPathDatasets()``` but should be ```this.pathsService.listPathDatasets()``` according with the code defined into CopybookDownloader.ts

Fix wrong call to listPathDatasets

---

com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolPreprocessor.g4
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestCpyNameWithSpecialChar.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/UseCaseSuite.java

fix: #273 Special characters are causing grammatical errors

Special characters are causing grammatical errors

---

com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/communications/ServerCommunications.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/AllTests.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/communications/ServerCommunicationsTest.java

In order to limit showing pop-ups silently log notifications that document analyzed with no errors.
close: #312 
fix: #308

Hide 'no errors found' message GH-312

---

clients/cobol-lsp-vscode-extension/releaseScripts/prepare.sh

Current "-NEXT" is pre-release identifier according the SemVer grammar.
After changing to "+NEXT" it will be a build metainfo.
This means that 0.11.1+NEXT and 0.11.1 will have the same precedence.

build: Change "-NEXT" suffix to "+NEXT"

---

clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksDownloaderTest.ts
clients/cobol-lsp-vscode-extension/src/__tests__/ZoweApiTest.ts
clients/cobol-lsp-vscode-extension/src/__tests__/ZoweErrorTest.ts
clients/cobol-lsp-vscode-extension/src/constants.ts
clients/cobol-lsp-vscode-extension/src/services/CopybooksDownloader.ts
clients/cobol-lsp-vscode-extension/src/services/ZoweApi.ts
clients/cobol-lsp-vscode-extension/src/services/ZoweError.ts

User was correctly notified if:
* Zowe profile have empty password
* MF API not accessible
* Zowe profile have wrong credentials
* dataset not found
Closes #237

Inform user about wrong credentials and stop sending other MF requests

---

clients/cobol-lsp-vscode-extension/src/__tests__/MiddlewareTest.ts
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java

Filtering fetch copybook events only for didOpen.

Add client tests for middleware

---

README.md

I've clarified the copybook retrieval setup procedure
- given the clearest possible instructions to access the COBOL LS extension preferences, since in Code4z the bitlang plugin has similar features in its extension preferences
- added a new step to add the zowe profile name
- clarified that copybooks need to be stored in PDSes.

Clarify copybook retrieval setup procedure

---

README.md

Several improvements to the readme text 
- introduction rewritten to be an intro to the extension rather than to an LSP
- copybook support turned into an L2 header 
- minor fixes

[Doc] Improve the readme introduction

---

Jenkinsfile
tests/theiaPrepare.sh
tests/theia_automation_lsp/robot_suites/lsp/local/firefox_lsp_local.robot

Right now we have all tests that fail with tag `Unstable`. After analysis, I saw that most of them failed because of defects not because they are unstable. 
So I propose to have a specific tag `DEFECT_OPEN` with a defect ID and also create a tag for tests that need updates (e.g., `NEED_UPDATE`). 
Also about warnings:
https://groups.google.com/forum/#!topic/robotframework-users/PsnmoUKnQpk
```
The old way to access items in a variable containing a list or a
dictionary has been `@{list}[0]` or `&{dict}[key]`, respectively. This
didn't work well with nested lists/dictionaries and RF 3.1 unified the
syntax to use `${list}[0]` or `${dict}[key]` instead [6]. The old
the syntax will be deprecated in RF 3.2 [7] and it's a good idea to change
to the new syntax already before that unless older RF …
```

IntegrationTests: Fix warnings and change tags 

---

clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.ts
clients/cobol-lsp-vscode-extension/src/__tests__/MiddlewareTest.ts
clients/cobol-lsp-vscode-extension/src/commands/FetchCopybookCommand.ts
clients/cobol-lsp-vscode-extension/src/services/CopybookDownloadService.ts
clients/cobol-lsp-vscode-extension/src/services/Middleware.ts

Doing existing profile check once for all list of downloading copybooks.
Not for each copybook individually.

Avoid many error messages for copybook downloading

---

com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/communications/Communications.java
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/communications/ServerCommunications.java

Purpose of this PR is to fix the issue #318 that inform user when a file under git vsc is opened with a popup that produce no value after all because the document is still evaluated by the LSP.

refactor: Remove popup message for GIT unsupported operation #318

---

README.md

Added a new section to the readme to warn of incompatibility with other COBOL related plugins (such as Z Open Editor).

Doc: Add compatibility section to readme

---

clients/cobol-lsp-vscode-extension/.releaserc.yaml

Disable adding comments to each PR about it is included into the
release.

ci: disable too many notifications from semantic-release tool

---

README.md

Updated the readme to remove Bitlang as a dependency for syntax coloring and add a section on Outline view which currently has the same bitlang dependency note.
Once we release outline view, the mentions of Bitlang will be removed.

[Doc] Update Bitlang dependency in readme

---

README.md

Minor update to the readme to add the new go to def on copybook names feature.

[Doc] add mention of go to definition on copybook names feature

---

clients/cobol-lsp-vscode-extension/.vscode/settings.json
com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java

Close #385 
Purpose of this PR is to clean up the problem area when the document is closed by the user.
According to the LSP protocol, client is responsible to:
- clean up problems notified in problem area
- restore the file text in the explorer removing the red font that highlight a file that contains problems.

Dispose diagnostic messages when user close the document #385

---

com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolLexer.g4
com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolParser.g4
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestExtraneousInputEOFExpecting.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestMissingCopybookAtBeginningNotBreaksSyntaxAnalysis.java
com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestReplacingWithDifferentPatternsShowsError.java

Pass copy enter and exit tags to a special channel to skip them on parsing

Fix syntax analysis termination with unexpected copy statements #464

---

README.md

(doc) clarify that local copybook folder paths need to be relative

---

server/pom.xml
server/src/test/java/com/broadcom/lsp/cobol/core/semantics/outline/RangeUtilsTest.java
server/src/test/java/com/broadcom/lsp/cobol/service/CopybookProcessingModeTest.java
server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCopybookCaching.java
server/src/test/java/com/broadcom/lsp/cobol/usecases/TestMarginAB.java
server/src/test/java/com/broadcom/lsp/cobol/usecases/TestOutlineTree.java

To avoid accidental use of the outdated infrastructure.
@grianbrcom 
@asatklichov

Exclude Junit 4 dependencies

---

server/pom.xml
server/src/main/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunications.java
server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
server/src/test/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunicationsTest.java

- Move unsupported files notification into problems console instead of logging
- Add unit tests for uncovered methods

Move unsupported files notification into problems console #173

---

server/src/main/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngine.java
server/src/main/java/com/broadcom/lsp/cobol/core/model/ResultWithErrors.java
server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderImpl.java

Add a method that will apply some operation to the errors and return the result with parametrized type to ResultWithErrors class in order to inline method calls that return values of that type.

Add an unwrap method to ResultWithErrors

---

server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/rewriter/CobolLineIndicatorProcessorImpl.java
server/src/test/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/rewriter/impl/CobolLineIndicatorProcessorImplTest.java

Seems like it was a leftover from the previous implementation.
Fix #605 
@asatklichov 
@grianbrcom

Fix exception on not formatted line

---

server/src/main/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngine.java
server/src/main/java/com/broadcom/lsp/cobol/core/visitor/InterruptingTreeListener.java
server/src/main/java/com/broadcom/lsp/cobol/domain/modules/EngineModule.java
server/src/test/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngineTest.java

`ParseTreeListener` is used to track the abstract syntax tree building and its methods called on each rule. So, it may be used to interrupt the parsing.

Make parsing interruptible 

---

server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java

There was a bug with the initial implementation. The error logs of doc analysis were not logged.

fix: Fix exception logging after analysis #546

---

server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
server/src/main/java/com/broadcom/lsp/cobol/service/CobolDocumentModel.java
server/src/test/antlr4/com/broadcom/usecase/UseCasePreprocessor.g4
server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCopybookNameWithQuotes.java
server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java

1. Normalize token name for copybooks implementation
2. Unit tests
3. Update usecase engine
3. +1 Use case for testing purpose

fix: Copybook with Name in Quotes Not Recognized #620

---

clients/cobol-lsp-vscode-extension/src/__tests__/LanguageClientServiceTest.spec.ts
clients/cobol-lsp-vscode-extension/src/extension.ts
clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
server/src/main/java/com/broadcom/lsp/cobol/LangServerBootstrap.java
server/src/main/java/com/broadcom/lsp/cobol/core/annotation/CheckServerShutdownState.java
server/src/main/java/com/broadcom/lsp/cobol/core/annotation/DisposableService.java
server/src/main/java/com/broadcom/lsp/cobol/core/annotation/HandleShutdownState.java
server/src/main/java/com/broadcom/lsp/cobol/core/annotation/NonSyntheticMethodMatcher.java
server/src/main/java/com/broadcom/lsp/cobol/domain/modules/ServiceModule.java
server/src/main/java/com/broadcom/lsp/cobol/service/CobolLanguageServer.java
server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
server/src/main/java/com/broadcom/lsp/cobol/service/CobolWorkspaceServiceImpl.java
server/src/main/java/com/broadcom/lsp/cobol/service/DisposableLanguageServer.java
server/src/test/java/com/broadcom/lsp/cobol/ConfigurableTest.java
server/src/test/java/com/broadcom/lsp/cobol/LangServerBootstrapTest.java
server/src/test/java/com/broadcom/lsp/cobol/TestModule.java
server/src/test/java/com/broadcom/lsp/cobol/core/annotation/HandleShutdownStateTest.java
server/src/test/java/com/broadcom/lsp/cobol/core/annotation/NonSyntheticMethodMatcherTest.java
server/src/test/java/com/broadcom/lsp/cobol/service/CobolLanguageServerTest.java
server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
server/src/test/java/com/broadcom/lsp/cobol/service/DocumentExtensionTests.java
server/src/test/java/com/broadcom/lsp/cobol/service/mocks/TestLanguageServer.java

Support Termination Requests #590
LSP spec says below about "shutdown" call:
"Clients must not send any notifications other than exit or requests to a server to which they have sent a shutdown request. If a server receives requests after a shutdown request those requests should error with InvalidRequest."
While the VScode API doesn't mention anything specific about the call in [references/vscode-api#Extension](https://code.visualstudio.com/api/references/vscode-api#Extension). It does mention it in [references/activation-events](https://code.visualstudio.com/api/references/activation-events)
And an issue [vscode issue](https://github.com/microsoft/vscode/issues/35196), mentions "VScode only wait for shutdown (e.g. for the promise to be resolved) and wait in total 5 seconds. There is not …

Support Termination Requests #590

---

server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
server/src/test/java/com/broadcom/lsp/cobol/usecases/TestReplacingForSeveralTokensInOneLine.java
server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSemanticErrorsFromCopybooksShownInDocument.java

The actual problem is that the `CobolVisitor` does not set the copybook ID for interval errors. 
Fix #652 
@asatklichov 
@grianbrcom 
@ap891843

Fix exposing semantic errors to document

---

clients/cobol-lsp-vscode-extension/package.json
server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
server/src/main/java/com/broadcom/lsp/cobol/service/delegates/communications/Communications.java
server/src/main/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunications.java
server/src/main/resources/resourceBundles/messages_en.properties
server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
server/src/test/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunicationsTest.java

Provide a new language ID for copybooks to allow coloring without applying syntax analysis. Remove language ID check on the server due to is guaranteed by the client.
Closes #654

Make copybook coloring work without analysis

---

.github/workflows/release.yml
release/release-it-release.json

The telemetry key was injected before the package build.
And wiped out after to not be present in repo.

ci: Build release package with correct telemetry key

---

server/src/main/java/com/broadcom/lsp/cobol/service/CopybookServiceImpl.java
server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
server/src/test/java/com/broadcom/lsp/cobol/service/CopybookServiceTest.java

The fix catch all possible exceptions from Guava cache and handle them correctly.
Closes #643

Fix analysis stop on a client exception

---

server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExecCicsHandleAidClear.java

HANDLE AID CLEAR() Produces a Syntax Error in EXEC CICS

---

CONTRIBUTING.md
server/localDev/logback.xml

Streaming the logging into stdout may cause JRPC issues.
Fixes #643

Disable console logging for production

---

server/pom.xml

In order to avoid package errors when opening the generated files

Explicitly specify the output directory for ANTLR

---

server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderImpl.java
server/src/main/java/com/broadcom/lsp/cobol/core/strategy/CobolErrorStrategy.java
server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java

False-positive indicator area errors are exposed to the log because optional calculations are greedy. They are changed to be lazy. Several similar issues are also fixed.
@grianbrcom 
@asatklichov 
@ap891843

Fix indicator check

---

README.md
clients/cobol-lsp-vscode-extension/README.md

- added the buttons at the top of the readme to the VS Code Client readme too
- added to the compatibility section that the extension is only supported on VS Code and Che

Add buttons to client readme / add to compatibility section in readme

---

clients/cobol-lsp-vscode-extension/src/__tests__/SettingsTest.spec.ts
clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
clients/cobol-lsp-vscode-extension/src/extension.ts
clients/cobol-lsp-vscode-extension/src/services/Settings.ts

The plugin doesn't try to modify workspaces settings on its own.
Closes #701

Remove prepopulating of settings.json with empty parameters for copybooks support

---

server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java

https://sonarcloud.io/project/issues?id=eclipse_che-che4z-lsp-for-cobol&resolved=false&severities=MAJOR&types=BUG

style: Refactor Optional to fix reliability issue

---

tests/README.md
tests/package.json

An npm `script` is a convenient way to bundle common shell commands. They are typically commands, which would normally be entered at the command line in order to run Cypress in CLI. 
Scripts are stored in a project's `package.json` file.  
You can check `4. Run Cypress` paragraph in the README file. 

feat: add npm scripts + update README

---

tests/package.json
tests/yarn.lock

In order to use those [changes ](https://github.com/eclipse/che-che4z/pull/32) in the core library, we should add `@types/node` here as well.

[UI_tests] Add @types/node

---

.huskyrc

Husky install git hooks it comes from UI tests.
Without husky config
pre-commit hook fails and you can't commit anything.

build: Add husky config file to the root

---

server/src/main/java/com/broadcom/lsp/cobol/core/semantics/GroupContext.java
server/src/main/java/com/broadcom/lsp/cobol/core/semantics/SemanticContext.java
server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
server/src/main/java/com/broadcom/lsp/cobol/service/delegates/validations/AnalysisResult.java
server/src/main/java/com/broadcom/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
server/src/test/java/com/broadcom/lsp/cobol/core/semantics/GroupContextTest.java
server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphRange.java
server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSectionRange.java
server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/UseCaseEngine.java

To build the CCF graph we need to have ranges of paragraphs and sections to check the usages belongs to the paragraph or to the section.
- 2 fields to the result added
- unit tests added
- use case tests added

feature: Collect and return ranges of paragraphs #777

---

tests/README.md
tests/cypress/integration/LSP/copybook.spec.js

You should configure Theia. Mount `test_files/test` as `home/test`. 
```
$ npm run cy:run -- --config baseUrl=https://theia --spec './cypress/integration/LSP/copybook.spec.js' -b chrome
TC318696 Load copybooks outside the workspace'
√ specify copybooks outside the current workspace ../test (9755ms)
√ specify copybooks outside the current workspace /home/test (6824ms)
√ specify copybooks outside the current workspace ../test/files (23463ms)
√ specify copybooks outside the current workspace /test (17033ms)
√ specify copybooks outside the current workspace ./test (12545ms)
√ specify copybooks outside the current workspace ./test/files (9677ms)
6 passing (1m)
```

[UI_tests] Add TC318696 test case

---

README.md

This is the doc change for US727864. I have removed the line saying relative paths are required but kept it as a recommendation due to the folders not being monitored for changes otherwise.
I have added info on how to resolve copybook names manually.

Describe new local copybook features in readme

---

server/src/main/java/org/eclipse/lsp/cobol/domain/event/model/AnalysisResultEvent.java
server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
server/src/main/java/org/eclipse/lsp/cobol/service/ExtendedApiService.java
server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java

Custom LSP implementation should support external calls.
This is needed to extend plugin functionality and plugins interaction.

feature: US729486 Extend LSP API #785

---

clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json

The whole division is colored. E.g. two words in "Data Division".
Closes #796

fix: coloring for divisions

---

server/src/main/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHover.java
server/src/test/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHoverTest.java

For some reason, the coloring didn't work if I specify "COBOL" as language.

fix: Add color to hover message

---

tests/cypress/integration/LSP/lsp.spec.js

```
Running:  LSP\lsp.spec.js                                                                 (1 of 1)
This is a LSP spec
TC319969 Provide the variables definition as documentation
√ Checks variable definition into VSC autocomplete documentation. (23395ms)
```

test: Add TC319969 test case

---

server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
server/src/main/java/org/eclipse/lsp/cobol/service/ExtendedApiResult.java
server/src/main/java/org/eclipse/lsp/cobol/service/ExtendedApiService.java
server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java

AnalysysResult is not serializable anymore and cannot be used as a result of the extended API call

fix: Make extended API call result serializable #823

---

server/src/test/java/org/eclipse/lsp/cobol/domain/databus/impl/DefaultDataBusBrokerTest.java
server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
server/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockTextDocumentService.java
server/src/test/java/org/eclipse/lsp/cobol/service/utils/TestThreadPoolExecutor.java
server/src/test/java/org/eclipse/lsp/cobol/service/utils/TestThreadPoolExecutorTest.java

Add TestThreadPoolExecutor to be able to run test syncronously.

refactor: change java unit tests to use only one thread

---

tests/.gitignore
tests/README.md
tests/cypress/integration/LSP/zowe.spec.js
tests/cypress/support/index.ts
tests/test_files/project/settings/clist_local.json
tests/test_files/project/settings/clist_nopass.json
tests/test_files/project/settings/clist_wrongpass.json
tests/test_files/zowe/profiles/zosmf/local.yaml
tests/test_files/zowe/profiles/zosmf/noPass.yaml
tests/test_files/zowe/profiles/zosmf/wrongPass.yaml
tests/yarn.lock

You need to mount the `zowe` folder
```
che-che4z-lsp-for-cobol/tests/test_files/zowe:/home/theia/.zowe
```
Then simply run the suite
```
npm run cy:run -- --config baseUrl=https://theia --spec cypress/integration/LSP/zowe.spec.js -b chrome --headless
```
```
This is a Zowe integration spec file
TC219568 Copybook is (semi) automatically downloaded
√ Checks that copybook was downloaded (9384ms)
TC219569 Nested Copybook is (semi) automatically downloaded
√ Checks that nested copybooks were downloaded (15042ms)
TC219570 Nested Copybook is (semi) automatically downloaded
√ Cobol file has a syntax error in case copybook is missing  (18179ms)
TC219571 Cobol file has a syntax error in case nested copybook is missing
√ Checks nested copybook missing (8914ms)
TC312870 Wrong profile credentials - …
```

test: Add Zowe test suite

---

server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
server/src/main/java/org/eclipse/lsp/cobol/core/engine/SyntaxTreeEngine.java
server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/AntlrVariableDefinitionNode.java
server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/Node.java
server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/NodeType.java
server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramNode.java
server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/RootNode.java
server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/SectionNode.java
server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/VariableDefinitionNode.java
server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/VariableUsageNode.java
server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableDefinitionDelegate.java
server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableUsageDelegate.java
server/src/test/java/org/eclipse/lsp/cobol/core/model/tree/NodeTest.java
server/src/test/java/org/eclipse/lsp/cobol/core/visitor/VisitorSemanticAnalysisTest.java
server/src/test/java/org/eclipse/lsp/cobol/usecases/TestProgramContexts.java

Each program context will be treated separately for variables error only.
Variable definitions, usages, etc works as before like in one context.

fix: correct variable definition error processing for multy context case

---

tests/cypress/integration/LSP/copybook.spec.js
tests/cypress/integration/LSP/lsp.spec.js
tests/cypress/integration/LSP/zowe.spec.js

Replacing Test Suite was disable because of this #837 bug. 
```
(Run Finished)
│ ✔  LSP\copybook.spec.js                     03:41       22       22        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  LSP\F101836.spec.js                      00:10        1        1        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  LSP\F102470.spec.js …
```

test: fix tests

---

clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json

String literal can ends with ', " or the end of the line.

fix: fix coloring for string literal in continuation line

---

server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
server/src/main/java/org/eclipse/lsp/cobol/core/engine/Timing.java

Example log piece:
```
Preprocessor: 946, parser: 19256, mapping: 19, visitor: 349, syntaxTree: 87, late error processing: 0
```

refactor: add timers inside CobolLanguageEngine

---

server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableDefinitionDelegate.java
server/src/main/resources/resourceBundles/messages_en.properties
server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableRedefineSameGroup.java

The redefining and redefined items must belong to the same group.

fix: fix REDEFINES clause for the same group

---

clients/cobol-lsp-vscode-extension/package-lock.json
server/pom.xml

bump guava in /server and y18n in /clients/cobol-lsp-vscode-extension

build : bump guava version in /server and y18n version in /clients/cobol-lsp-vscode-extension

---

server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VariableUsageDelegate.java
server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java

Instead of three dataNames we can use one.

refactor: Unify dataName parser rule

---

clients/cobol-lsp-vscode-extension/.vscodeignore
clients/cobol-lsp-vscode-extension/package.json

lodash/fs and jsonschema/schema was excluded

build: exclude some folders from vsix package

---

README.md

Updated the list of things supported by autocomplete to include CA IDMS DML statements; also compacted the list somewhat as it was getting a bit long.
For the next release.

Update autocomplete list to add IDMS statements

---

tests/cypress/integration/LSP/F95833.spec.js
tests/cypress/integration/LSP/F97476.spec.js
tests/cypress/integration/LSP/copybook.spec.js
tests/cypress/integration/LSP/lsp.spec.js
tests/cypress/support/index.ts

Unfortunately, Cypress doesn't support `win1251` and `ibm1253`, so I've added only `utf-8` encoding. 

test: add TC326105 and fix other tests

---

tests/cypress/integration/LSP/copybook.spec.js
tests/cypress/integration/LSP/lsp.spec.js

Results:
```
────────────────────────────────────────────────────────────────────────────────────────────────────
Running:  LSP/copybook.spec.js                                                            (1 of 2)
This is a Copybook spec
TC327253 Support COPY MAID statements
√ Support COPY MAID statements (14274ms)
1 passing (14s)
(Results)
│ Tests:        1                                                                                │
│ Passing:      1                                                                                │
│ Failing:      0                                                                                │
│ Pending:      0 …
```

test: Add new test cases

---

README.md

Small update to the readme for IDMS copybooks. Some pages will be published on IDMS techdocs detailing what needs to be done on the mainframe side so added a link to the IDMS doc too.

Update README with IDMS copybook sentence

---

tests/cypress/integration/LSP/lsp.spec.js

Testing #1039
```
(Run Finished)
Spec                                              Tests  Passing  Failing  Pending  Skipped
│ ✔  LSP/lsp.spec.js                          00:39        5        5        -        -        - │
✔  All specs passed!                        00:39        5        5        -        -        -
```

test: Add TC328483

---

tests/cypress/integration/LSP/copybook.spec.js

Fixes #1107. 
Results:
```
(Run Finished)
│ ✔  LSP/copybook.spec.js                     00:43        3        3        -        -        - │
✔  All specs passed!                        00:43        3        3        -        -        -  
```

test: add more wait time for encoding tests

---

Jenkinsfile
tests/package.json
tests/yarn.lock

Fixes #1113
> When running cypress run previous to 8.0, some browsers would launch headed while others were launched headless by default. In 8.0, we've normalized all browsers to launch as headless by default.

test: Update Cypress version to 8.5.0

---

server/pom.xml

chore: Exclude unused checker dependency

---

server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidAllowsOnlyValidLevelNumbers.java
server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidIsNotResolvedInProcedureDivision.java
server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestMultiTokenError.java
server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestParametrised.java
server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestReplacing.java
server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestWithCopybook.java
server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestWithErrorCheck.java
server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestWithSubroutines.java

Closes #1208
COPY MAID statements that do not have the level number specified should not be resolved. It will disable such statements in the PROCEDURE DIVISION.

Disable COPY MAID statements without numbers 

---

clients/cobol-lsp-vscode-extension/src/__tests__/CommentCommandTest.spec.ts
clients/cobol-lsp-vscode-extension/src/commands/CommentCommand.ts

Now it's possible to comment one continuation line

refactor: change toggle comment line behavior

---

README.md
clients/cobol-lsp-vscode-extension/package.json

Let users know that `.cpy` is recognized as a COBOL copybook and `.cobol` as a cobol file.

Add .cobol as a supported copybook extension

---

README.md
clients/cobol-lsp-vscode-extension/README.md

Client readme was not updated for 1.0.0 - updating it now. Also fixed a typo on the new addition to the main readme.
We might want to consider doing a 1.0.1 release for this as the rebranding (removal of CA) has been overdue for some time.
Apologies for the fork PR, Eclipse have rescinded my access to the repos because of some red tape and aren't getting back to me

Update client readme for 1.0.0

---

clients/cobol-lsp-vscode-extension/package.json

The extension seems to work fine when post-changing it (I've done that in the 1.0.0-vsix and so far did not get any strange error message).
Please check if you need the 1.56 version and consider a downgrade, when not.

downgrade to vscode 1.55

---

server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ElementaryItemNode.java
server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/MultiTableDataNameNode.java
server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/TableDataNameNode.java
server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/UsageFormat.java
server/src/test/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHoverTest.java

fix: variable declaration hover converts hyphens to underscores

---

server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtil.java
server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
server/src/test/java/org/eclipse/lsp/cobol/usecases/TestGlobalVariableAreReferencedInsideNestedProgram.java

fix: Allow global FD variable usage inside nested programs.

---

server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/SetUpDownByStatement.java
server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetIndexDoOutproduceErrorForSendingFieldLevel77.java

fix: Allow level 77 variable to be used for setting fields.

---

README.md

Zowe v2 conformance update. Moved the info out of prerequisites and into an integration section.

Zowe v2 conformance update

---

clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
clients/cobol-lsp-vscode-extension/src/__tests__/services/LanguageClientServiceTest.spec.ts

AS IS:
Following tests are failing:
1. Test LanguageClientService starts language client
2. Check plugin extension for cobol starts
TO  BE:
SERVER_ID constant adjusted, with some indentation autoformatting

fix: cobol constants in test

---

clients/cobol-lsp-vscode-extension/package.json

Update local copybook settings description to remove the word "relative" - using relative paths is now just a recommendation, not a requirement. Solves #1511

Update local copybook setting description

---

server/engine/src/main/java/org/eclipse/lsp/cobol/domain/modules/ServiceModule.java
server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolLanguageServer.java
server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookReferenceRepo.java
server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookReferenceRepoImpl.java
server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookService.java
server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookServiceImpl.java
server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
server/engine/src/main/java/org/eclipse/lsp/cobol/service/utils/SettingsParametersEnum.java
server/engine/src/test/java/org/eclipse/lsp/cobol/TestModule.java
server/engine/src/test/java/org/eclipse/lsp/cobol/service/ClientServerIntegrationTest.java
server/engine/src/test/java/org/eclipse/lsp/cobol/service/CobolLanguageServerTest.java
server/engine/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
server/engine/src/test/java/org/eclipse/lsp/cobol/service/copybooks/CopybookReferenceRepoImplTest.java
server/engine/src/test/java/org/eclipse/lsp/cobol/service/copybooks/CopybookServiceTest.java
server/engine/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockTextDocumentService.java
server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseUtils.java

Update diagnostics when copybook are updated.
1. any change in dialect (e.g. MAID) copybook will result in rescanning and updating	of error list in opened program.
2. works even without saving the changed copybook.

feat: Update diagnostics when copybook are updated

---

Jenkinsfile

Remove jenkins parameter for integration tests

build: Remove jenkins parameter for integration tests

---

server/dialect-daco/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/DaCoParser.g4
server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/daco/TestDaCoTableRowAddStatement.java

This change may require updating of DaCo documentation because allowing SPACE and literal string is probably not captured there.

fix: Allow SPACE and literal in DaCo ROW ADD stmt

---

server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookIdentificationServiceBasedOnContent.java
server/engine/src/test/java/org/eclipse/lsp/cobol/service/copybooks/CopybookIdentificationServiceBasedOnContentTest.java

Update copybook identification regex to support all use cases

fix: Update copybook identification regex to support  all use cases

---

clients/cobol-lsp-vscode-extension/src/__mocks__/glob.ts
clients/cobol-lsp-vscode-extension/src/__mocks__/vscode.ts
clients/cobol-lsp-vscode-extension/src/__tests__/commands/SmartTabCommandTest.spec.ts
clients/cobol-lsp-vscode-extension/src/commands/SmartTabCommand.ts
clients/cobol-lsp-vscode-extension/src/services/util/FSUtils.ts

Please test it on windows!
Steps:
1. have a simple COBOL program with a copybook, ("CB1.cpy")
2. specify a path to the copybook folder using glob pattern, for example, "COPYBOO?'
3. Verify that "COPYBOOK/CB1.cpy" is resolved by COBOL LS

Fix: support glob with more then * magic chars

---

server/engine/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestUtfLiteral.java

support utf literal.
Ref - https://www.ibm.com/docs/en/cobol-zos/6.3?topic=cobol-using-utf-8-literals

fix: support utf literal

---

server/common/src/main/java/org/eclipse/lsp/cobol/common/symbols/SymbolTable.java
server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestMultipleProgramInADocument.java

Support same program id for multiple programs in same document

fix: Support same program id for multiple programs in same document

---

clients/cobol-lsp-vscode-extension/package.json

Add empty sting as default for copybook extensions

fix: Add empty sting as default for copybook extensions

---

server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java

do not show progress notification for copybooks as we don't analyse copybooks.

fix: do not show progress notification for copybooks

---

server/dialect-idms/src/main/java/org/eclipse/lsp/cobol/dialects/idms/IdmsDialect.java
server/dialect-idms/src/test/java/org/eclipse/lsp/cobol/dialects/idms/usecases/TestCopyIdmsVariablesForNotAllowedLevels.java

Do not adjust level numbers  66/77/88 for copy IDMS variables

fix: Do not adjust level numbers  66/77/88 for copy IDMS variables

---

clients/cobol-lsp-vscode-extension/src/services/util/FSUtils.ts

An issue: local copybook resolution doesn't work for special characters like %, #, $
Steps to test:
1. Create a folder with a special character in the name
2. Add it to the local copybooks path
3. Add a copybook to this folder
4. Use this copybook in a COBOL program
Expected:
- copybook is resolved

Fix: support folders with special (url) characters
