eclipse/che-che4z-lsp-for-cobol

- clients/cobol-lsp-vscode-extension/package.json
Signed-off-by: Gianni Pucillo <gianni.pucillo@broadcom.com>
> Update the plugins properties #3

- com.ca.lsp.cobol/lsp-service-cobol/pom.xml
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyDocumentModel.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/completions/AbstractCompletionStorage.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/positive/CobolTextRegistry.java
Signed-off-by: Andrei Temnikov <andrei.temnikov@broadcom.com>
> Log4J usages replaced with Logback for the logging consistency #7

- clients/cobol-lsp-vscode-extension/src/extension.ts
Signed-off-by: Ramy Abdalla <ramy.abdalla@broadcom.com>
Applied changes to check for java installation before launching LSP server
> adding java check before starting server #11

- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyLanguageServerImpl.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/Highlights.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/references/References.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/AllTests.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/HighlightsTest.java
As per Issue #26 syntax Highlighting function has been implemented and unit test provided
> Adding highlighting issue #26

- clients/cobol-lsp-vscode-extension/.vscodeignore
- clients/cobol-lsp-vscode-extension/jest.config.js
- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/JavaVersionCheck.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/JavaVersionCheckTest.ts
- clients/cobol-lsp-vscode-extension/src/extension.ts
Checking expected Java version (1.8), intended to resolve #35
Added tests with Jest to client
> Java version matching #35

- CHANGELOG.md
Changes to reflect new version 0.8.3
> 0.8.3 Changelog

- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/completions/Completions.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/completions/KeywordCompletion.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/completions/ParagraphCompletion.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/completions/SnippetCompletion.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/completions/VariableCompletion.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/AllTests.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/completions/ParagraphCompletionTest.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/delegates/completions/SnippetCompletionTest.java
adding Paragraph completion suggestion as per #28
> Adding paragraph completion

- com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/broadcom/lsp/cdi/LangServerCtx.java
- com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/util/PreprocessorCleanerService.java
In order to fix the code smell found by SonarCloud
> Remove unused imports and unnecessary comment

- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/validations/Analysis.java
Signed-off-by: Kalugina Tatyana <strekoz-zka@mail.ru>
> Make Analysis synchronized in order to avoid ConcurrentModificationException #79

- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyDocumentModel.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyDocumentModelTest.java
> Add check for line correctness in order to prevent StringIndexOutOfBoundsException

- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/Communications.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/delegates/ServerCommunications.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
> Engineering excellence

- com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolParser.g4
- com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolPreprocessor.g4
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestSkipStatement.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/UseCaseSuite.java
> Add SKIP statement

- com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/antlr4/com/ca/lsp/core/cobol/parser/CobolLexer.g4
> Fix SKIP3 statement

- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
Hide the constant variable from external
> change variable access visibility

- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
The full implementation will be provided by the issue #173
After the merge keep the related issue open
> Create temporary solution for not supported gitfs

- CHANGELOG.md
- Jenkinsfile
- clients/cobol-lsp-vscode-extension/CHANGELOG.md
- clients/cobol-lsp-vscode-extension/package-lock.json
- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/server/note.md
- clients/cobol-lsp-vscode-extension/src/extension.ts
- com.ca.lsp.cobol/lsp-core-cobol-parser/pom.xml
- com.ca.lsp.cobol/lsp-core-domain/pom.xml
- com.ca.lsp.cobol/lsp-service-cobol/pom.xml
- com.ca.lsp.cobol/pom.xml
Please verify if the version is changed everywhere and is pointing to the new tag
> Release 0.10.1

- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
Unnecessary map collection was removed.
> Refactor MyTextDocumentService::observerCallback

- clients/cobol-lsp-vscode-extension/src/extension.ts
Just add:
```json
"broadcom-cobol-lsp.server": {
"port": 1044
}
```
to your settings.json and start LSP server on localhost:1044
> Add property to enable TCP connection to LSP server

- com.ca.lsp.cobol/lsp-core-cobol-parser/pom.xml
- com.ca.lsp.cobol/lsp-core-domain/pom.xml
- com.ca.lsp.cobol/lsp-service-cobol/pom.xml
- com.ca.lsp.cobol/pom.xml
The current version is specified in the "revision" property.
Project version sets via the "revision" property.
> Refactoring pom.xml: putting the project version in property.

- CHANGELOG.md
- clients/cobol-lsp-vscode-extension/CHANGELOG.md
- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/CopybooksDownloader.ts
- clients/cobol-lsp-vscode-extension/src/commands/EditDatasetPaths.ts
- clients/cobol-lsp-vscode-extension/src/extension.ts
- clients/cobol-lsp-vscode-extension/src/services/CopybookResolver.ts
- clients/cobol-lsp-vscode-extension/src/services/CopybooksCodeActionProvider.ts
- clients/cobol-lsp-vscode-extension/src/services/PathsService.ts
> A comma-separated list of datasets editor

- README.md
Added:
- Copybooks now downloaded manually
- Copybook autocomplete feature
> New updates on Copybooks

- tests/theia_automation_lsp/inc/theia/constants.py
- tests/theia_automation_lsp/robot_suites/lsp/local/firefox_lsp_local.robot
Change files panel title.
Change hint message according existing code.
> Update integration tests.

- clients/cobol-lsp-vscode-extension/src/CopybooksDownloader.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/DownloadQueueTest.ts
- clients/cobol-lsp-vscode-extension/src/services/DownloadQueue.ts
> Fix multiple error messages while downloading copybooks

- README.md
- clients/cobol-lsp-vscode-extension/README.md
- made one final change to readme (added a link to instructions to create a zosmf profile)
- copied main readme over to VSC client readme
> TI release preparation

- Jenkinsfile
- tests/theiaPrepare.sh
- tests/theia_automation_lsp/robot_suites/lsp/local/firefox_lsp_local.robot
> Use shared volume to transfer package.

- Jenkinsfile
- tests/theiaPrepare.sh
> Use copy artifacts plugin

- README.md
- clients/cobol-lsp-vscode-extension/CHANGELOG.md
- clients/cobol-lsp-vscode-extension/README.md
Simplification of the VS Code changelog to just list broad features rather than every PR (these can be listed in the main changelog). Please feel free to make any additions.
> Release 0.11 changelog simplification

- README.md
- clients/cobol-lsp-vscode-extension/README.md
These updates to the readme are for the next release - they come from an email from Scott.
> Further updates to readme - comments from Scott.

- Jenkinsfile
- tests/theiaPrepare.sh
> Use custom images

- Jenkinsfile
- tests/theiaPrepare.sh
> Precreate .zowe folder

- clients/cobol-lsp-vscode-extension/.vscodeignore
> Exclude release tool files from vsix package

- README.md
- clients/cobol-lsp-vscode-extension/CHANGELOG.md
- clients/cobol-lsp-vscode-extension/README.md
Minor fixes to readme (one link) and changelog (one wrong indent)
> Minor fixes to readme and changelog

- clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksPathGeneratorTest.ts
- clients/cobol-lsp-vscode-extension/src/extension.ts
- clients/cobol-lsp-vscode-extension/src/services/CopybookFix.ts
- clients/cobol-lsp-vscode-extension/src/services/CopybooksPathGenerator.ts
- clients/cobol-lsp-vscode-extension/src/services/ProfileService.ts
fix: "Profile not set" pop-up #270
> "Profile not set" pop-up

- CONTRIBUTING.md
Some advice and requirements for contributors to the committing process.
> doc: Add committing requirements for contributors

- CHANGELOG.md
- clients/cobol-lsp-vscode-extension/CHANGELOG.md
Purpose of this PR is to apply linting to the changeslog files of the master branch.
@grianbrcom: I didn't included #219 since I remember you said was a kind of not relevant thing to add in the changelog, in case I am wrong please let me know and I will update the changelog.
> doc: Fix changelog 0.11.1

- Jenkinsfile
Using the right "workspace" variable.
> ci: Fix Jenkins deploy stage

- README.md
Specified in the readme file that the java PATH variable has to be configured
> Add java path to prerequisites in the readme file

- Jenkinsfile
- tests/reportCollection.sh
> ci: Fix integration testing artifacts collecting

- tests/reportCollection.sh
> Fix webdriver log name for collection

- clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/broadcom/lsp/cdi/module/service/ServiceModule.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/ClientService.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/ClientServiceImpl.java
> Settings request PoC.

- clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
- com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/copybook/AnalyseCopybookTask.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/ClientService.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/ClientServiceImpl.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyLanguageServerImpl.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/InitializeConfigurationTest.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyLanguageServerImplTest.java
> Fix analyse and rewrite ClientService

- clients/cobol-lsp-vscode-extension/src/extension.ts
- clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
- clients/cobol-lsp-vscode-extension/src/services/Middleware.ts
> Refactoring Middleware client part

- clients/cobol-lsp-vscode-extension/src/extension.ts
- clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
> Fix middleware issue

- clients/cobol-lsp-vscode-extension/src/services/Middleware.ts
> Fix cobol name extraction

- Jenkinsfile
> Added Jenkins params to run integration tests

- clients/cobol-lsp-vscode-extension/src/__tests__/MiddlewareTest.ts
- clients/cobol-lsp-vscode-extension/src/services/Middleware.ts
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/broadcom/lsp/cdi/module/service/ServiceModule.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/ClientService.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CobolWorkspaceServiceImpl.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/CopybookServiceImpl.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/MyLanguageServerImpl.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/SettingsService.java
- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/SettingsServiceImpl.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/TestModule.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/CopybookServiceTest.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/MyLanguageServerImplTest.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/WorkspaceServiceTest.java
Add the header to Middleware.ts
> refactor: Rename ClientService to SettingsService

- clients/cobol-lsp-vscode-extension/jest.config.js
- clients/cobol-lsp-vscode-extension/src/__tests__/JavaCheckTest.ts
- clients/cobol-lsp-vscode-extension/src/services/JavaCheck.ts
> test: Improve code coverage for JavaCheck

- clients/cobol-lsp-vscode-extension/src/__tests__/ZoweApiTest.ts
> test: Add ZoweApi unit tests for client

- tests/theia_automation_lsp/README.md
Add the Linux section.
Signed-off-by:  Maryna Nalbandian maryna.nalbandian@broadcom.com
> Update tests/theia_automation_lsp/README.md file

- clients/cobol-lsp-vscode-extension/package.json
> refactor: Delete unused plugin properties #23

- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/utils/SettingsParametersEnum.java
> Change settings paths on the server side #393

- com.ca.lsp.cobol/lsp-service-cobol/src/main/java/com/ca/lsp/cobol/service/WatcherServiceImpl.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/service/WatcherServiceImplTest.java
> Add watchers also to folders #395

- com.ca.lsp.cobol/lsp-core-domain/src/test/java/com/broadcom/lsp/domain/cobol/event/CopybookEventSubscribersTest.java
> test: Fix types of asserted events

- CHANGELOG.md
- clients/cobol-lsp-vscode-extension/CHANGELOG.md
- clients/cobol-lsp-vscode-extension/README.md
- client readme file updated with same content as main file
- First draft added for the changelog (in the root file). If you agree with the content, I will copy it over to the client changelog before merging to dev.
> Updates to Readme and Changelog for version 0.12.0

- com.ca.lsp.cobol/pom.xml
This dependency is out of date and not used anymore
> build: Remove unused dependency

- clients/cobol-lsp-vscode-extension/.releaserc.yaml
- clients/cobol-lsp-vscode-extension/releaseScripts/prepare.sh
> ci: Disable changelog updating on release

- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
> Syntax coloring support

- README.md
Updated the Java version in prereqs from version 8 to version 11
> [Doc] Update Java version in readme

- com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
- com.ca.lsp.cobol/lsp-service-cobol/src/test/java/com/ca/lsp/cobol/usecases/TestMarginAB.java
I've fixed the CobolVisitor.java messages which were discussed in the parking lot
> Proofread cobolvisitor messages

- clients/cobol-lsp-vscode-extension/releaseScripts/prepare.sh
Now script also updates the version in package-lock.json
> Fix version updating CI script

- CHANGELOG.md
- README.md
- clients/cobol-lsp-vscode-extension/CHANGELOG.md
- clients/cobol-lsp-vscode-extension/README.md
- references to Bitlang removed from readme
- note about extended sources folder added to readme
- client changelog updated with major updates
I think I need more info for the main changelog - we seem to list every PR here under the headers Features / Bug Fixes along with the PR numbers.
> Updates to readme and changelog before release

- NOTICE.md
> docs: Add NOTICE file

- clients/cobol-lsp-vscode-extension/package-lock.json
- clients/cobol-lsp-vscode-extension/package.json
> build: update Zowe Imperative version

- com.ca.lsp.cobol/lsp-core-cobol-parser/src/main/resources/logback.xml
- com.ca.lsp.cobol/lsp-core-domain/src/main/resources/logback.xml
- com.ca.lsp.cobol/lsp-service-cobol/src/main/resources/logback.xml
> remove broadcom from log path #456

- Jenkinsfile
> correct server path for Jenkins

- clients/cobol-lsp-vscode-extension/releaseScripts/prepare.sh
> adjust path for vsix generation

- clients/cobol-lsp-vscode-extension/server/note.md
- clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
> adjust server path for client

- server/README.md
- server/src/test/java/com/ca/lsp/cobol/positive/PositiveTest.java
- server/src/test/resources/logback-test.xml
> fix: delete un-used log level and readme file

- server/src/main/java/com/ca/lsp/cobol/service/MyLanguageServerImpl.java
- server/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
- server/src/main/java/com/ca/lsp/cobol/service/delegates/validations/AnalysisResult.java
- server/src/main/java/com/ca/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
- server/src/main/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngine.java
- server/src/main/java/com/ca/lsp/core/cobol/semantics/CobolVariableContext.java
- server/src/main/java/com/ca/lsp/core/cobol/semantics/SemanticContext.java
- server/src/main/java/com/ca/lsp/core/cobol/semantics/outline/NodeType.java
- server/src/main/java/com/ca/lsp/core/cobol/semantics/outline/OutlineNodeNames.java
- server/src/main/java/com/ca/lsp/core/cobol/semantics/outline/OutlineTreeBuilder.java
- server/src/main/java/com/ca/lsp/core/cobol/semantics/outline/RangeUtils.java
- server/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
- server/src/test/java/com/ca/lsp/cobol/service/DocumentExtensionTests.java
- server/src/test/java/com/ca/lsp/cobol/service/MyLanguageServerImplTest.java
- server/src/test/java/com/ca/lsp/cobol/service/MyTextDocumentServiceTest.java
- server/src/test/java/com/ca/lsp/cobol/service/delegates/completions/CopybookCompletionTest.java
- server/src/test/java/com/ca/lsp/cobol/service/delegates/completions/ParagraphCompletionTest.java
- server/src/test/java/com/ca/lsp/cobol/service/delegates/completions/VariableCompletionTest.java
- server/src/test/java/com/ca/lsp/cobol/usecases/TestOutlineTree.java
- server/src/test/java/com/ca/lsp/cobol/usecases/TestOutlineTreeLineNumbers.java
- server/src/test/java/com/ca/lsp/core/cobol/engine/CobolLanguageEngineTest.java
- server/src/test/java/com/ca/lsp/core/cobol/semantics/outline/RangeUtilsTest.java
- server/src/test/java/com/ca/lsp/core/cobol/visitor/VisitorSemanticAnalysisTest.java
> feat: Outline view support

- server/src/main/java/com/ca/lsp/core/cobol/preprocessor/sub/line/reader/impl/CobolLineReaderImpl.java
- server/src/test/java/com/ca/lsp/cobol/usecases/TestExtraSymbolsNotCauseErrorOnNextLine.java
> docs: Adjust the error message for 80 chars limit

- Jenkinsfile
> fix jenkins pipeline

- .github/workflows/changelog.yml
- .github/workflows/release.yml
- Jenkinsfile
- clients/cobol-lsp-vscode-extension/server/note.md
- clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
- release/release-it-changelog.json
- release/release-it-release.json
- release/version-extract.js
- server/pom.xml
GH action for changelog draft generation was added.
GH action for
releasing was added.
Jenkinsfile changed to use branch and build number
in package version.
> ci: Change versioning pipeline

- .github/workflows/changelog.yml
- .github/workflows/release.yml
> ci: explicitly specify release-it version

- server/src/main/java/com/broadcom/lsp/domain/cobol/databus/api/CopybookRepository.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/databus/api/DataBusBroker.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/databus/impl/AbstractDataBusBroker.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/databus/impl/CopybookRepositoryLRU.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/databus/impl/DefaultDataBusBroker.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/databus/model/CopybookStorable.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/AnalysisFinishedEventSubscriber.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/CopybookDepEventSubscriber.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/FetchedCopybookEventSubscriber.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/FetchedSettingsEventSubscriber.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/RequiredCopybookEventSubscriber.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/RunAnalysisEventSubscriber.java
- server/src/main/java/com/broadcom/lsp/domain/cobol/event/impl/UnknownEventSubscriber.java
- server/src/main/java/com/ca/lsp/cobol/service/MyTextDocumentService.java
- server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/CopybookRepositoryLRUTest.java
- server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusGetFromCacheBadTest.java
- server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusGetFromCacheHappyTest.java
- server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusStoreHappyTest.java
- server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusSubscribeHappyTest.java
- server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DataBusUnSubscribeTest.java
- server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DatabusBrokerTest.java
- server/src/test/java/com/broadcom/lsp/domain/cobol/databus/impl/DatabusEventSubscriptionE2ETest.java
There are no reason for that annotation.
> refactor: Delete SneakyThrows

- README.md
Update readme to specify that we only support IBM Enterprise COBOL (email with Scott)
> (doc) COBOL version compatibility note

- server/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
- server/src/test/java/com/ca/lsp/cobol/usecases/TestSpellCheckNotAppliedForVariables.java
> Disable spellchecker for variables

- server/src/main/java/com/ca/lsp/core/cobol/visitor/CobolVisitor.java
- server/src/test/java/com/ca/lsp/cobol/usecases/TestExecCicsContainerStatementsArgumentsOrder.java
- server/src/test/java/com/ca/lsp/cobol/usecases/TestIncorrectTableCallUnderlined.java
- server/src/test/java/com/ca/lsp/cobol/usecases/TestIndexDefinition.java
> Introduce index variable definition support

- server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
- server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderDelegate.java
- server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CobolLineReaderImpl.java
- server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/reader/CompilerDirectivesTransformation.java
- server/src/main/java/com/broadcom/lsp/cobol/domain/modules/EngineModule.java
- server/src/test/java/com/broadcom/lsp/cobol/core/AbstractCobolLinePreprocessorTest.java
> DI for preprocessor

- clients/cobol-lsp-vscode-extension/.vscodeignore
> exclude generated scannerwork folders from vsix

- clients/cobol-lsp-vscode-extension/.vscodeignore
> build: Include node_modules into VSIX package

- server/src/main/java/com/broadcom/lsp/cobol/core/model/Locality.java
- server/src/main/java/com/broadcom/lsp/cobol/core/model/variables/ElementItem.java
- server/src/main/java/com/broadcom/lsp/cobol/core/strategy/Messages.java
- server/src/test/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/rewriter/impl/CobolLineIndicatorProcessorImplTest.java
- server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusBrokerTest.java
- server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusConfigProvider.java
- server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusEventSubscriptionE2ETest.java
> code refactoring with lombok annotations

- server/src/main/java/com/broadcom/lsp/cobol/service/CopybookService.java
- server/src/main/java/com/broadcom/lsp/cobol/service/CopybookServiceImpl.java
- server/src/test/java/com/broadcom/lsp/cobol/positive/FolderTextRegistry.java
- server/src/test/java/com/broadcom/lsp/cobol/service/delegates/validations/UseCaseUtils.java
Should fix the copybooks resolution issue that appeared after merging the sync copybook service and folder-based positive tests pull requests together.
> Positive tests fix

- server/src/test/java/com/broadcom/lsp/cobol/service/CopybookServiceTest.java
Test case for cover the middleware throwing an error was added.
> test: Increase CopybookServiceTests

- server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/main/resources/resourceBundles/messages_en.properties
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestMarginAB.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphNotDefined.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphSectionDefined.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestVaryingCorrect.java
- server/src/test/resources/message/messages_fr.properties
- server/src/test/resources/resourceBundles/messages_en.properties
> improvement: Improve Semantic Analysis for Paragraphs #526

- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCallVariableUsages.java
> fix: variable usage works in a call statement

- clients/cobol-lsp-vscode-extension/snippets.json
> add new code snippets exec-sql-include and exec-cics

- server/src/main/java/com/broadcom/lsp/cobol/core/annotation/CheckThreadInterruption.java
- server/src/main/java/com/broadcom/lsp/cobol/core/annotation/HandleThreadInterruption.java
- server/src/main/java/com/broadcom/lsp/cobol/core/annotation/ThreadInterruptAspect.java
- server/src/main/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngine.java
- server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/TextPreprocessorImpl.java
- server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorImpl.java
- server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/main/java/com/broadcom/lsp/cobol/domain/modules/ServiceModule.java
- server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
- server/src/main/java/com/broadcom/lsp/cobol/service/CopybookServiceImpl.java
- server/src/test/java/com/broadcom/lsp/cobol/core/annotation/HandleThreadInterruptionTest.java
- server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
Interrupt Analysis on Closing Request
> Interrupt Analysis on Closing Request

- server/src/main/java/com/broadcom/lsp/cobol/core/semantics/GroupContext.java
- server/src/main/java/com/broadcom/lsp/cobol/core/semantics/SemanticContext.java
- server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/main/java/com/broadcom/lsp/cobol/domain/modules/ServiceModule.java
- server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/CompletionOrder.java
- server/src/main/java/com/broadcom/lsp/cobol/service/delegates/completions/SectionCompletion.java
- server/src/main/java/com/broadcom/lsp/cobol/service/delegates/references/SectionLocations.java
- server/src/main/java/com/broadcom/lsp/cobol/service/delegates/validations/AnalysisResult.java
- server/src/main/java/com/broadcom/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
- server/src/test/antlr4/com/broadcom/usecase/UseCasePreprocessor.g4
- server/src/test/java/com/broadcom/lsp/cobol/TestModule.java
- server/src/test/java/com/broadcom/lsp/cobol/core/engine/CobolLanguageEngineTest.java
- server/src/test/java/com/broadcom/lsp/cobol/core/semantics/GroupContextTest.java
- server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/CompletionsChainTest.java
- server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/ConstantCompletionTest.java
- server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/SectionCompletionTest.java
- server/src/test/java/com/broadcom/lsp/cobol/service/delegates/completions/SnippetCompletionTest.java
- server/src/test/java/com/broadcom/lsp/cobol/service/delegates/references/SectionLocationsTest.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestCompilerDirectivesNotCauseErrors.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestErrorsInDifferentFiles.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExecCicsGetMainStatementArgumentsOrder.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestMisspelledKeywordWarningInCorrectPosition.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphDefined.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestParagraphNotDefined.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSameCopybookStatementsInDifferentPlacesTreatedAsDifferentEntries.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSectionDefined.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestSyntaxErrorTraversedThroughHierarchy.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/TestData.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/UseCaseEngine.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
Implement completion and definition/reference support for sections inside the PROCEDURE DIVISION
> Add Language Features Support for Sections #502

- clients/cobol-lsp-vscode-extension/package-lock.json
- clients/cobol-lsp-vscode-extension/package.json
Experimental: not for release.
> Use latest zowe version

- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestExecCicsSendStatementsArgumentsOrder.java
Fix: #617 
@grianbrcom
@asatklichov
@ap891843
@Nurkambay
> Fix syntax error on ERASE in CICS SEND

- server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
New didChange Request Should Interrupt Previous Analysis #616
> feat : New didChange Request Should Interrupt Previous Analysis #616

- server/src/main/java/com/broadcom/lsp/cobol/LangServerBootstrap.java
- server/src/main/java/com/broadcom/lsp/cobol/domain/databus/impl/AbstractDataBusBroker.java
- server/src/main/java/com/broadcom/lsp/cobol/domain/databus/impl/DefaultDataBusBroker.java
- server/src/main/java/com/broadcom/lsp/cobol/domain/modules/DatabusModule.java
- server/src/main/java/com/broadcom/lsp/cobol/domain/modules/EngineModule.java
- server/src/main/java/com/broadcom/lsp/cobol/domain/modules/ServiceModule.java
- server/src/main/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunications.java
- server/src/main/java/com/broadcom/lsp/cobol/service/utils/CustomThreadPoolExecutor.java
- server/src/main/java/com/broadcom/lsp/cobol/service/utils/CustomThreadPoolExecutorService.java
- server/src/test/java/com/broadcom/lsp/cobol/LangServerBootstrapTest.java
- server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusSubscribeBadTest.java
- server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusSubscribeHappyTest.java
- server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DataBusUnSubscribeTest.java
- server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusBrokerTest.java
- server/src/test/java/com/broadcom/lsp/cobol/domain/databus/impl/DatabusConfigProvider.java
- server/src/test/java/com/broadcom/lsp/cobol/service/delegates/communications/ServerCommunicationsTest.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestResponsesNotContainLineBreaks.java
- server/src/test/java/com/broadcom/lsp/cobol/utils/CustomThreadPoolExecutorTest.java
> using custom thread pool executor #615

- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
@grianbrcom 
@asatklichov 
@ap891843 
@Nurkambay
> Remove unused LD rule

- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/__tests__/ChangeDefaultZoweProfileTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/LanguageClientServiceTest.spec.ts
[Experimental] LocalCopybookResolverTest fails randomly #626
> fix : [Experimental] LocalCopybookResolverTest fails randomly #626

- server/src/main/java/com/broadcom/lsp/cobol/service/CobolTextDocumentService.java
- server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
Complete outline Request for Unsupported Files #653
> fix : Complete outline Request for Unsupported Files #653

- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestVaryingSupportForFileAssignment.java
Varying Shows Error in FILE-CONTROL #623
> fix : Support "Varying" in FILE-CONTROL #623

- server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestProgramNameIsCaseInsensitive.java
Check PROGRAM-ID is Case In-Sensitive #594
> fix : Check PROGRAM-ID is Case In-Sensitive #594

- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CICSParser.g4
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestKeywordInProgramId.java
Support COBOL CICS intersected keyword in Program ID #600
> fix : Support COBOL CICS intersected keyword in Program ID #600

- README.md
Troubleshooting and Subroutine Support sections added to Readme file for the next release.
> Troubleshooting and Subroutine Support sections added

- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolParser.g4
- server/src/main/java/com/broadcom/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/test/java/com/broadcom/lsp/cobol/usecases/TestVariableDefinitionsAllowFILLER.java
> Allow FILLER for level 77 definition

- CHANGELOG.md
- clients/cobol-lsp-vscode-extension/CHANGELOG.md
@asatklichov 
@grianbrcom 
@ap891843 
@Nurkambay
> Provide changelog for release 0.16.0

- server/src/test/java/com/broadcom/lsp/cobol/service/CobolTextDocumentServiceTest.java
> Stabilize CobolTextDocuemntServiceTest

- clients/cobol-lsp-vscode-extension/src/services/copybook/DownloadQueue.ts
Fixing Coverity issue CID 49751
> Explicitly use 'this' in DownloadQueue.ts

- CONTRIBUTING.md
@grianbrcom 
@asatklichov 
@ap891843
> doc: Fix project path in CONTRIBUTING.md

- README.md
- clients/cobol-lsp-vscode-extension/README.md
Update client readme for new release
> Update client readme

- server/src/main/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/VariableUtils.java
- server/src/test/java/com/broadcom/lsp/cobol/core/preprocessor/delegates/util/VariableUtilsTest.java
> VariableUtils refactoring

- server/pom.xml
specify the output dir for ANTLR
> build : specify the output dir for ANTLR

- server/src/main/java/com/broadcom/lsp/cobol/core/visitor/VariableDefinitionDelegate.java
> VariableDefinitionDelegate refactoring

- README.md
> remove sentence about case sensitivity in copybook names

- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/Db2SqlParser.g4
> refactor: add COMMENT as db-generic-name and null check

- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessor.g4
- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CommonCobolLexer.g4
> fix : Improve mapping mismatch caused due to SQL grammar

- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/Db2SqlParser.g4
> refactor: Fix SQL expressions

- README.md
> Readme update for DB2 SQL

- Jenkinsfile
> ci: Secure string interpolation in Jenkinsfile

- README.md
> Change Java version

- server/src/main/antlr4/com/broadcom/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
> fix : fix comment mismatch bewteen pre-processor and cobol-engine.

- clients/cobol-lsp-vscode-extension/src/__tests__/CopybookResolveURITest.spec.ts
- clients/cobol-lsp-vscode-extension/src/services/util/FSUtils.ts
> feat: Support copybooks outside the current workspace #755

- tests/.gitignore
- tests/.huskyrc
- tests/.lintstagedrc
- tests/.prettierignore
- tests/.prettierrc
- tests/README.md
- tests/cypress.json
- tests/package.json
- tests/yarn.lock
This PR fixes #765 and #761.  
Probably remove `node_modules` and `yarn.lock`. Perform `yarn install`. 
Then run `npm run ts:build`. 
Simply run `npm run cy:run:all:headless` or `npm run cy:run:all:headless -- --config baseUrl=https://theia`. 
After finishing the test run perform `npm run generate:html:report`. This will generate the final HTML report. See the example in the attachments. 
```
(Run Finished)
│ ✔️  LSP\copybook.spec.js                     03:28       20       16        -        4 …
```
> Upgrade Cypress to 6.4.0. Add mochawesome reporter. Add configs.

- tests/cypress/integration/LSP/F102470.spec.js
- tests/cypress/integration/LSP/F95834.spec.js
- tests/cypress/integration/LSP/F96117.spec.js
- tests/cypress/integration/LSP/F96125.spec.js
- tests/cypress/integration/LSP/F97476.spec.js
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
- tests/test_files/project/settings/basic.json
- tests/test_files/project/settings/empty.json
- tests/test_files/project/settings/subroutines.json
- tests/test_files/project/settings/testing.json
Check this [pull request](https://github.com/eclipse/che-che4z/pull/34). 
```
(Run Finished)
│ ✔  LSP\copybook.spec.js                     04:49       26       22        -        4        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  LSP\F101836.spec.js                      00:11        1        1        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✖ …
```
> Add general Theia configs method 

- tests/.gitignore
- tests/cypress/integration/LSP/F96117.spec.js
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
- tests/package.json
- tests/test_files/project/settings/basic.json
- tests/test_files/project/settings/empty.json
- tests/test_files/project/settings/subroutines.json
- tests/test_files/project/settings/testing.json
- tests/yarn.lock
FIxes #792 
```
(Run Finished)
│ ✔  LSP\copybook.spec.js                     04:00       26       22        -        4        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  LSP\F101836.spec.js                      00:09        1        1        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✖  LSP\F102470.spec.js                      02:00        3        1        1 …
```
> test: Remove broadcom naming from configurations

- clients/cobol-lsp-vscode-extension/src/__tests__/LanguageClientServiceTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/extension.ts
- clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
1. Implementation: Populate public extended API let other plugins use COBOL LS plugin features
1. Unit tests
> feature: US729482 Create COBOL LS VSC extension public API #801

- clients/cobol-lsp-vscode-extension/src/__tests__/CopybookResolveURITest.spec.ts
> Use Che-Theia compatible Nodejs (v. 10.5-11.15) methods

- tests/cypress/integration/LSP/lsp.spec.js
- tests/test_files/project/HOVER.CBL
Results:
```
$ npm run cy:run -- --spec 'cypress/integration/LSP/lsp.spec.js' --headless -b chrome --config baseUrl=https://theia
(Run Finished)
│ ✔  LSP\lsp.spec.js                          00:28        1        1        -        -        - │
✔  All specs passed!                        00:28        1        1        -        -        -  
```
Signed-off-by: Maryna Nalbandian …
> test: add TC319689(hovering) test

- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestReplacingSameCopybookTwice.java
Thanks to @ap891843 for providing the fix.
> fix: two COPY REPLACE statements work wrong

- Jenkinsfile
Hey, @temanbrcom, this is special for you, dude!
Check this https://ci.eclipse.org/che4z/job/LSP%20for%20COBOL/job/mavenIntegration/2/
Enjoy!
> ci: Add maven integraion

- server/src/style/checkstyle.xml
- server/src/style/javaHeader.txt
Checkstyle was changed to check header with regex.
> style: Allow having any year in the copyright header

- server/src/test/java/org/eclipse/lsp/cobol/positive/CobolText.java
> style: make readable name for positive tests

- server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
- server/src/main/java/org/eclipse/lsp/cobol/core/engine/SyntaxTreeEngine.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/AntlrVariableDefinitionNode.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/Node.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/NodeType.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramEndNode.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramIdNode.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/ProgramNode.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/VariableUsageNode.java
- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/test/java/org/eclipse/lsp/cobol/core/model/tree/NodeTest.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestProgramContexts.java
Program end name check fixed.
Variable errors check fixed.
> fix: fixed nested program parsing

- Jenkinsfile
> ci: Trim Jenkins pod label

- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/__tests__/SmartTabCommandTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/commands/SmartTabCommand.ts
- clients/cobol-lsp-vscode-extension/src/constants.ts
- clients/cobol-lsp-vscode-extension/src/extension.ts
> feat: Customize TAB button #841

- tests/README.md
- tests/cypress/integration/LSP/lsp.spec.js
> test: Add small enchantments

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestExecCicsStatementMustCodedInAreaB.java
> EXEC CICS block should be defined in Area B #858

- tests/package.json
- tests/yarn.lock
> test: Upgrade Cypress to 7.1.0

- Jenkinsfile
> ci: Increase maven memory

- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/ReplacingServiceImpl.java
- server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/impl/ReplacingServiceImplTest.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopybookReplacePatterns.java
> fix: replacement work if replacing or replaced text contains BY

- clients/cobol-lsp-vscode-extension/src/commands/SmartTabCommand.ts
As a User I want TAB functionality to be tuned following way:
1. SHIFT+TAB in the middle of the line would move the text (on the right side) left to the previous column or 4 spaces (if there is no column)
1. if the cursor is at the beginning of the line, TAB should move the cursor and the whole line to the next column
> feat: Tune TAB functionality #906

- tests/.gitignore
- tests/README.md
- tests/cypress/integration/LSP/F97476.spec.js
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
- tests/cypress/plugins/index.js
- tests/cypress/support/index.ts
- tests/package.json
- tests/yarn.lock
This PR contains:
* Allure Report instead of muchawesome
* Removing `.skip` tests because of [issue](https://github.com/Shelex/cypress-allure-plugin/issues/65)
Simply run suite and then run npm-scrips `allure*`.
> test: Add Allure Report

- tests/cypress.json
- tests/cypress/integration/LSP/F95833.spec.js
- tests/cypress/integration/LSP/F96117.spec.js
- tests/cypress/integration/LSP/F97476.spec.js
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
- tests/package.json
- tests/yarn.lock
`cypress-tags` temporarily is not working (check this [issue](https://github.com/annaet/cypress-tags/issues/58) ). So I've decided to comment those tests are not working (have tags `flaky,flaky_theia,bug,investigation`). So `CYPRESS_EXCLUDE_TAGS` or `CYPRESS_INCLUDE_TAGS` are not working. 
```
(Run Finished)
│ ✔  LSP/copybook.spec.js                     03:17       22       22        -        -        - │
├──────────────────────────────────────────────────────────────────────────────────────────────── …
```
> test: workaround for cypress-tags and other small fixes

- server/src/main/java/org/eclipse/lsp/cobol/LangServerBootstrap.java
- server/src/test/java/org/eclipse/lsp/cobol/LangServerBootstrapTest.java
Should fix also freezing tests on Linux.
> Make socket streams closeable

- CHANGELOG.md
- clients/cobol-lsp-vscode-extension/CHANGELOG.md
I have removed duplicated and internal changes, also the bug fixes for not released features. Please, check if missed something or removed by accident. The date specified in the changelog files is not agreed yet, so it may change.
> Create changelog for 0.19.0

- README.md
Add sentence to mention that enabling copybook support also enables those features on CCF.
> Add sentence about CCF copybook support

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReadyAfterIfNotProducesError.java
> Allow IDMS statements in conditional block #952

- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtil.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/AbstractVariable.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/NodeConverter.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariablesHasChildren.java
> Fix hover for group items

- server/src/main/java/org/eclipse/lsp/cobol/service/utils/WorkspaceFileService.java
Fix #956 
Should be tested with UI tests before merging.
> Fix loading copybooks with any encoding

- server/src/main/java/org/eclipse/lsp/cobol/service/CFASTBuilderImpl.java
> Fix incorrect IF statement parsing

- tests/cypress/integration/LSP/F97476.spec.js
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
After #980.
@nalmabrcom please, check that it works.
> test: Adjust invalid definition error message

- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsCopy.java
> refactor: Cancel name length check for COPY IDMS

- server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/NodeConverter.java
- server/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/DocumentationUtils.java
- server/src/test/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHoverTest.java
Fix #994
Requires manual testing
> Show condition names in variable description

- tests/cypress/integration/LSP/F95833.spec.js
- tests/cypress/integration/LSP/F96117.spec.js
- tests/cypress/integration/LSP/F97476.spec.js
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
- tests/package.json
- tests/yarn.lock
This bug is fixed [58](https://github.com/annaet/cypress-tags/issues/58) in `cypress-tags`. Let's revert temporary solution. 
> test: Return back cypress tags functionality

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/TechnicalLexer.g4
- server/src/test/antlr4/org/eclipse/usecase/UseCasePreprocessor.g4
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSemicolonNotAllowedInIdentificationDivision.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSemicolonNotAllowedOnNotTerminatingPositions.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestStatementTerminationWithSemicolons.java
> Allow semicolons as statement terminators

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessor.g4
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/GrammarPreprocessorListenerImpl.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithQualifier.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithQualifierMissingCopybook.java
> Allow COPY MAID clauses with qualifiers

- clients/cobol-lsp-vscode-extension/.vscodeignore
> Fix Black Duck issues

- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestStatementTerminationWithSemicolons.java
> Fix test that fails after merging

- clients/cobol-lsp-vscode-extension/.vscodeignore
> build: Fix stack trace in Theia

- clients/cobol-lsp-vscode-extension/README.md
> Update client readme for 0.20.0

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ConditionDataNameNode.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ValueInterval.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionNode.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtil.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/ConditionDataName.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/NodeConverter.java
- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
- server/src/main/java/org/eclipse/lsp/cobol/service/delegates/completions/DocumentationUtils.java
- server/src/test/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableDefinitionUtilTest.java
- server/src/test/java/org/eclipse/lsp/cobol/core/model/variables/ConditionDataNameTest.java
- server/src/test/java/org/eclipse/lsp/cobol/service/delegates/hover/VariableHoverTest.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/Test88ThruHover.java
> Add padding for 88 level variables hover

- Jenkinsfile
- tests/.gitignore
- tests/cypress.json
- tests/cypress/integration/LSP/copybook.spec.js
- tests/package.json
- tests/yarn.lock
> Add reporter and other changes

- tests/cypress/integration/LSP/lsp.spec.js
> add wait to test

- Jenkinsfile
> add froze-lockfile for yarn

- server/src/main/java/org/eclipse/lsp/cobol/core/model/variables/ConditionDataName.java
> Fix code duplication

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapSectionDoesntProduceNPE.java
> Fix server freeze on typos in MAP SECTION

- Jenkinsfile
- tests/.gitignore
- tests/cypress.json
- tests/cypress/integration/LSP/F95833.spec.js
- tests/cypress/integration/LSP/F96117.spec.js
- tests/cypress/integration/LSP/F96125.spec.js
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
- tests/cypress/plugins/index.js
- tests/cypress/support/index.ts
- tests/package.json
- tests/test_files/project/settings/basic.json
- tests/tsconfig.json
- tests/yarn.lock
Nightly builds for development branch was added.
Added a parameter to run UI tests on demand.
All PR's from "nalmabrcom" will trigger UI tests.
Co-authored-by: Maryna Nalbandian <maryna.nalbandian@broadcom.com>
> ci: add UI tests

- Jenkinsfile
> ci: remove deploy stage

- tests/cypress/integration/LSP/F96125.spec.js
> test: exclude failing UI test

- tests/cypress.json
> test: revert retries functionality

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestObtainAnyAfterMoveParsedCorrectly.java
> Fix consuming extra tokens by statements

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSLexer.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlLexer.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/TechnicalLexer.g4
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestFileDescriptor.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsCopy.java
> refactor: don't show comments on hover on FD/SD variables.

- README.md
> SCS conflict for automatic copybook retrieval

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIncomplete88DoesNotProduceNPE.java
> Fix exception on an incomplete 88 definition

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTypingExecDoesNotProduceException.java
> Fix exception on incomplete EXEC statement

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/EmbeddedLanguagesListener.java
- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestExecVarDoesNotProduceNPE.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTypingExecDoesNotProduceException.java
> Fix an exception on EXEC variable name

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEndIfDoesNotProduceError.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableEndDoesNotProduceNPE.java
> Fix exception on END token

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestNoExceptionOnEmptyUsage.java
> Fix exception on empty USAGE clause

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestHalfTypedVariableDefinition.java
> fix: Fix throwing an exception on half typed variable definition

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetDownByDoesNotProduceExceptions.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetUpDoesNotProduceExceptions.java
> fix: Fix exception on incomplete SET UP statement

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDeclarativesSection.java
> fix: Fix throwing an exception on half typed DECLARATIVES Section

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestOccursToDoesNotProduceExceptions.java
> Fix exception on incomplete OCCURS TO clause

- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
@nalmabrcom please, check if they pass successfully
> Fix UI tests

- clients/cobol-lsp-vscode-extension/snippets.json
Signed-off-by: Teri Schnitt <teri.schnitt@broadcom.com>
Added snippets for shell template, IDMS sections and COPY IDMS statements.
> feat: Add IDMS snippets #704

- server/src/test/java/org/eclipse/lsp/cobol/positive/TypingTest.java
> test: add timeout for typing tests

- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/LocalityMappingUtils.java
- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/EmbeddedLanguagesListener.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestExecCicsDoesNotFreezeAnalysis.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestExecSqlDoesNotFreezeAnalysis.java
> Fix server freeze on EXEC statement

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/src/main/java/org/eclipse/lsp/cobol/core/MessageServiceParser.java
An example of prepending validation by pattern.
> Refactor validation of subschema name

- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/VisitorHelper.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestNoStringIndexOutOfBoundsOnExecSql.java
> Fix exception on typing EXEC SQL

- tests/yarn.lock
Signed-off-by: Maryna Nalbandian maryna.nalbandian@broadcom.com
> test: bump semver-regex in /tests

- tests/cypress/integration/LSP/F102470.spec.js
- tests/cypress/integration/LSP/F95833.spec.js
- tests/cypress/integration/LSP/F96125.spec.js
- tests/cypress/integration/LSP/F97476.spec.js
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
- tests/package.json
> test: Add more tests to CI

- tests/cypress/integration/LSP/F101836.spec.js
Fixes #1106
```
(Run Finished)
│ ✔  LSP/F101836.spec.js                      00:11        1        1        -        -        - │
✔  All specs passed!                        00:11        1        1        -        -        -  
```
> test: fix Outline test

- tests/cypress/integration/LSP/F96117.spec.js
Fixes #1108 
```
(Run Finished)
Spec                                              Tests  Passing  Failing  Pending  Skipped
│ ✔  LSP/F96117.spec.js                       01:18        2        2        -        -        - │
✔  All specs passed!                        01:18        2        2        -        -        -
```
> test: fix TC247908 and TC247996

- server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestMultiTokenError.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestParametrised.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestPositiveCase.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestReplacing.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestWithCopybook.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestWithErrorCheck.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/example/TestWithSubroutines.java
> test: add UseCase examples

- clients/cobol-lsp-vscode-extension/package.json
Hopefully this fixes issue #1040
> Syntax fix in package.json

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsBindStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsLoadStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReadyStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsSections.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsStartpageStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsTransferStatement.java
Signed-off-by: Teri Schnitt <teri.schnitt@broadcom.com>
> Fix IDMS entity length error locations #704

- clients/cobol-lsp-vscode-extension/src/extension.ts
> fix: Change the extension initialisation order #1040

- Jenkinsfile
Upgrading packages from git repos not working (especially `@eclipse/che-che4z` ), so this is a workaround for now.
> ci: Update Jenkinsfile for cypress container

- Jenkinsfile
- clients/cobol-lsp-vscode-extension/package-lock.json
- clients/cobol-lsp-vscode-extension/package.json
> ci: downgrade vsce version

- Jenkinsfile
- tests/cypress/integration/LSP/F102470.spec.js
- tests/cypress/integration/LSP/F95833.spec.js
- tests/cypress/integration/LSP/F95834.spec.js
- tests/cypress/integration/LSP/F96117.spec.js
- tests/cypress/integration/LSP/F97476.spec.js
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
- tests/cypress/integration/LSP/zowe.spec.js
- tests/yarn.lock
> test: Use predefined selectors

- server/src/test/java/org/eclipse/lsp/cobol/positive/TypingTest.java
> test: improve typing tests parallelism

- server/src/main/java/org/eclipse/lsp/cobol/service/CopybookServiceImpl.java
- server/src/test/java/org/eclipse/lsp/cobol/service/CopybookServiceTest.java
> Fix resolving SQLCA from workspace

- server/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
- server/src/main/java/org/eclipse/lsp/cobol/core/strategy/CobolErrorStrategy.java
- server/src/main/java/org/eclipse/lsp/cobol/core/strategy/ErrorMessageHelper.java
- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/EmbeddedLanguagesListener.java
- server/src/main/java/org/eclipse/lsp/cobol/domain/modules/EngineModule.java
- server/src/test/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngineTest.java
- server/src/test/java/org/eclipse/lsp/cobol/core/strategy/ErrorMessageHelperTest.java
> fix: Fix thread issue with error  strategy for diff parsers.

- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/CopybookResolveURITest.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksPathGeneratorTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/constants.ts
- clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookDownloadService.ts
- clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookURI.ts
- clients/cobol-lsp-vscode-extension/src/services/copybook/CopybooksPathGenerator.ts
> feat: Support USS file download for copybooks.

- Jenkinsfile
- tests/cypress.json
- tests/cypress/integration/LSP/F102470.spec.js
- tests/cypress/integration/LSP/F95833.spec.js
- tests/cypress/integration/LSP/F95834.spec.js
- tests/cypress/integration/LSP/F96117.spec.js
- tests/cypress/integration/LSP/F97476.spec.js
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
- tests/cypress/integration/LSP/zowe.spec.js
- tests/cypress/support/index.ts
- tests/package.json
- tests/tsconfig.json
- tests/yarn.lock
Completely refactored `lsp.spec.js`. CI will fail because `che-che4z` part should be merged first. 
> test: Add GitPod support. Part I. 

- Jenkinsfile
> ci: change theia image

- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/SearchPattern.java
- server/src/test/antlr4/org/eclipse/usecase/UseCasePreprocessor.g4
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopybookReplacePatterns.java
> fix: Make quoted string replacement work.

- clients/cobol-lsp-vscode-extension/README.md
> doc: Update README.md

- README.md
Readme updates for the Zowe Explorer dependency.
> Readme updates for ZE dependency

- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/CopybooksPathGeneratorTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/constants.ts
- clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookDownloadService.ts
- clients/cobol-lsp-vscode-extension/src/services/copybook/CopybooksPathGenerator.ts
> fix: Prompt proper error message for copybook download.

- tests/cypress/integration/LSP/F101836.spec.js
- tests/cypress/integration/LSP/F102470.spec.js
- tests/cypress/integration/LSP/F95833.spec.js
- tests/cypress/integration/LSP/F95834.spec.js
- tests/cypress/integration/LSP/F96117.spec.js
- tests/cypress/integration/LSP/F97476.spec.js
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/zowe.spec.js
Because of this [issue ](https://github.com/gitpod-io/openvscode-server/issues/294) it is not possible for now to check all scenarios containing any settings to be applied. So, fo now I can't verify it with all changes here. 
> test: Add changes to work on VSC

- clients/cobol-lsp-vscode-extension/src/__tests__/CopybookDownloadServiceTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/ProfileUtilsTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/constants.ts
- clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookDownloadService.ts
- clients/cobol-lsp-vscode-extension/src/services/util/ProfileUtils.ts
> fix: Give option to download Zowe Explorer.

- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/__mocks__/vscode.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/CommentCommandTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/commands/CommentCommand.ts
- clients/cobol-lsp-vscode-extension/src/extension.ts
> feat: add comment line ability

- server/src/main/java/org/eclipse/lsp/cobol/domain/modules/EngineModule.java
- server/src/main/java/org/eclipse/lsp/cobol/service/CobolLanguageServer.java
- server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
- server/src/main/java/org/eclipse/lsp/cobol/service/CobolWorkspaceServiceImpl.java
- server/src/main/java/org/eclipse/lsp/cobol/service/Configuration.java
- server/src/main/java/org/eclipse/lsp/cobol/service/ConfigurationImpl.java
- server/src/test/java/org/eclipse/lsp/cobol/service/CobolLanguageServerTest.java
- server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
- server/src/test/java/org/eclipse/lsp/cobol/service/ConfigurationImplTest.java
- server/src/test/java/org/eclipse/lsp/cobol/service/WorkspaceServiceTest.java
> refactor: update the read config on init or change

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEndIfAndDot.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEndIfDoesNotProduceError.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsBindStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsConDisconnectStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsDcStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsEraseStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsFindObtainStatements.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsGetStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsKeepStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapInStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsMapOutStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsModifyMapStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsReadyStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsRollbackStatement.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetUpDownBy.java
> fix: make dot optional after END-IF

- server/src/main/java/org/eclipse/lsp/cobol/service/CFASTBuilderImpl.java
> fix: Process only program Node for CCF tree.

- server/src/main/java/org/eclipse/lsp/cobol/core/model/CopyStatementModifier.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/CopybookHierarchy.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/CopybookModificationListener.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/GrammarPreprocessorListenerImpl.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/AbstractCopybookAnalysis.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/CopybookName.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/DialectCopybookAnalysis.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/PredefinedCopybookAnalysis.java
- server/src/main/java/org/eclipse/lsp/cobol/service/CopybookServiceImpl.java
- server/src/test/java/org/eclipse/lsp/cobol/positive/CobolText.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithKmkRequestsCorrectFile.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithQualifier.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithQualifierMissingCopybook.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestOutlineTree.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestOutlineTreeLineNumbers.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/AnnotatedDocumentCleaning.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/PredefinedCopybookUtils.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/TestData.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseEngine.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCasePreprocessorListener.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseUtils.java
@Nurkambay 
@niharikasw91 
@VitGottwald
> Process COPY MAID qualifiers

- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableNode.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseEngine.java
> refactor: Unify retrieval logic in UseCaseEngine

- server/pom.xml
Signed-off-by: Vit Gottwald <vit.gottwald@gmail.com>
> fix: Java Compile Error

- clients/cobol-lsp-vscode-extension/src/commands/SmartTabCommand.ts
It can also be a fix for #1231
> fix: Fix tab key for suggestions

- server/src/main/java/org/eclipse/lsp/cobol/core/model/CopyStatementModifier.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/ProcessingConstants.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/CopybookModificationListener.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/GrammarPreprocessorListenerImpl.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/LastVariableNameListener.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/copybooks/analysis/DialectCopybookAnalysis.java
- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/CobolParserUtils.java
- server/src/main/resources/resourceBundles/messages_en.properties
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWRK.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkDifferentCase.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkDoesNotTakeNameFrom88.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkShortName.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkShowsErrorAfter77.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkShowsErrorAfterFiller.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkShowsErrorAfterVariableWithoutName.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestCopyMaidWithWrkShowsErrorOnShortVariableName.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestPseudoTextContentConstraint.java
@VitGottwald have fun.
@Nurkambay, @niharikasw91 please, review.
> Provide support for WRK usage of COPY MAID

- clients/cobol-lsp-vscode-extension/package-lock.json
> build: Update client dependencies

- clients/cobol-lsp-vscode-extension/package.json
> refactor: hide maid copybook configurations

- clients/cobol-lsp-vscode-extension/.vscodeignore
> ci: Exclude QS library from client

- clients/cobol-lsp-vscode-extension/.vscodeignore
@ap891843, can you please test it manually?
> ci: Exclude old libraries from client

- server/src/test/java/org/eclipse/lsp/cobol/positive/TypingTest.java
Before:
```
[INFO] Total time:  7 d 03:57 h
```
After:
```
[INFO] Total time:  4 d 22:56 h
```
> test: Speed up typing tests

- clients/cobol-lsp-vscode-extension/package.json
No changes are made to the server capabilities which handle this feature.
> fix: Hide supported language feature from settings.

- README.md
- clients/cobol-lsp-vscode-extension/package.json
This PR aims to update Readme by adding 2 sub-sections about the syntax analysis and dialects features.
Signed-off-by: ik673626 <igor.kazmyr@broadcom.com>
> (Doc) Update Readme  

- server/src/main/java/org/eclipse/lsp/cobol/service/CachingConfigurationService.java
- server/src/test/java/org/eclipse/lsp/cobol/service/CachingConfigurationServiceTest.java
> fix: Provide default features list when no features are set in settings

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIdmsIfStatement.java
> fix: if condition may consist of dialects

- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/QualifiedReferenceNode.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableNode.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/VariableUsageNode.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestProgramContexts.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestWorkingStoragePredefinedVariables.java
> feat: show many definitions for a variable

- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDuplicatedVariableDefinition.java
> test: add test for show many definitions for a variable

- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/rewriter/CobolLineIndicatorProcessorImpl.java
- server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/TestCommentLines.java
- server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/rewriter/impl/CobolLineIndicatorProcessorImplTest.java
> fix : remove comments after preprocesing

- server/src/main/java/org/eclipse/lsp/cobol/service/CobolLanguageServer.java
- server/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
- server/src/test/java/org/eclipse/lsp/cobol/service/CobolLanguageServerTest.java
- server/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
> feat: Support folding for COBOL #1164

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSLexer.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSParser.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolPreprocessorLexer.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlLexer.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlParser.g4
- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/TechnicalLexer.g4
- server/src/main/java/org/eclipse/lsp/cobol/core/visitor/EmbeddedLanguagesListener.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestEndIfDoesNotProduceError.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSemicolonAllowedOnTerminatingPositions.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSemicolonNotAllowedInIdentificationDivision.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetUpDownBy.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestStatementTerminationWithSemicolons.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestTyposOnCompilerDirectives.java
> fix: Allow semicolon separator.

- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/FigurativeConstants.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/QualifiedReferenceNode.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestVariableUsageForFigurativeConstants.java
> fix: Support figurative constant in variable usage.

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/DaCoParser.g4
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDaCoTableRowModifyStatement.java
> fix: Modify DaCo row modify grammar rule.

- server/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/rewriter/CobolLineIndicatorProcessorImpl.java
- server/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/rewriter/impl/CobolLineIndicatorProcessorImplTest.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestContinuationLine.java
> fix: Concatenate continuous lines properly.

- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/statements/SetUpDownByStatement.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/EffectiveData.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/ElementaryNode.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/IndexItemNode.java
- server/src/main/java/org/eclipse/lsp/cobol/core/model/tree/variables/StandAloneDataItemNode.java
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetIndexDoOutproduceErrorForSendingFieldOfTypeInteger.java
> fix: Allow set field to be set to any integer elementary variable.

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestIntrinsicFunctionCall.java
> fix: Allow MAX as allowed intrinsic function name.

- server/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/DaCoParser.g4
- server/src/test/java/org/eclipse/lsp/cobol/usecases/TestDaCoTableRowInsertStatement.java
> fix: Update DaCo grammar for ROW INSERT.

- CHANGELOG.md
- clients/cobol-lsp-vscode-extension/CHANGELOG.md
> docs: Update changelog

- clients/cobol-lsp-vscode-extension/package-lock.json
- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/__tests__/services/reporter/TelemetryServiceTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/services/reporter/TelemetryReporterImpl.ts
Update telemetry and test dependency
> Update telemetry and test dependency

- .github/workflows/release.yml
- Jenkinsfile
> fix: Fix server startup

- clients/cobol-lsp-vscode-extension/package-lock.json
- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/__tests__/services/reporter/TelemetryServiceTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/services/reporter/TelemetryReporterImpl.ts
> Bump telemetry dependency

- server/engine/src/main/resources/org/eclipse/lsp/cobol/service/delegates/completions/LanguageSnippetsDaCo.json
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/delegates/completions/SnippetCompletionTest.java
Modify Snippets for DaCo Return Status and Field statements in DaCo parser #1126
> feat: Modify Snippets for DaCo Return Status and Field statements

- clients/cobol-lsp-vscode-extension/src/__tests__/services/LanguageClientServiceTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
Add test for LS initialization for native builds
> test: Add test for LS initialization for native builds

- README.md
- clients/cobol-lsp-vscode-extension/README.md
- clients/cobol-lsp-vscode-extension/package-lock.json
- clients/cobol-lsp-vscode-extension/package.json
eclipsefdn/eca  fails as release commit is performed by git-bot
> Sync development and master

- clients/cobol-lsp-vscode-extension/package-lock.json
- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/__tests__/services/reporter/TelemetryServiceTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/services/reporter/TelemetryReporterImpl.ts
- tests/cypress/integration/LSP/copybook.spec.js
- tests/cypress/integration/LSP/lsp.spec.js
> refactor: Revert telemetry version bump

- server/engine/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestFDRecordContainsClause.java
Update File Description grammar as per docs.
> fix: Update File Description grammar as per docs.

- clients/cobol-lsp-vscode-extension/package.json
> fix: Remove the unused command

- server/engine/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSTranslatorLexer.g4
- server/engine/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CICSTranslatorParser.g4
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/engine/dialects/DialectService.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/engine/dialects/cicsTranslator/CICSTranslatorDialect.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/engine/dialects/cicsTranslator/CICSTranslatorVisitor.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/AnalysisConfig.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CachingConfigurationService.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/ConfigurationService.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/CachingConfigurationServiceTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestCICSTranslatorOptions.java
Support CICS translator options. For more details visit  https://www.ibm.com/docs/en/cics-ts/6.1?topic=compilation-using-cics-translator
> feature: Support CICS translator options

- server/engine/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/IdmsParser.g4
> fix: Update the ON clause to handle the NEXT SENTENCE.

- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/__tests__/services/SettingsTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/services/copybook/CopybooksCodeActionProviderTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/constants.ts
- clients/cobol-lsp-vscode-extension/src/extension.ts
- clients/cobol-lsp-vscode-extension/src/services/LanguageClientService.ts
- clients/cobol-lsp-vscode-extension/src/services/Settings.ts
- server/engine/src/main/resources/META-INF/native-image/reflect-config.json
- server/engine/src/main/resources/META-INF/native-image/resource-config.json
Provide settings to enable native build. Update meta data for native images.
> feature: Provide settings to enable native build

- server/engine/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlLexer.g4
- server/engine/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/Db2SqlParser.g4
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/visitor/Db2SqlVisitor.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CachingConfigurationService.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlAllSetStatements.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlCloseStatement.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlExecuteImmediateStatement.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlOpenStatement.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlSelectIntoStatement.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlSelectStatement.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestSqlValuesIntoStatement.java
Fix Db2 host variable references.
> fix: Fix Db2 host variable references.

- clients/cobol-lsp-vscode-extension/package-lock.json
- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/__tests__/commands/ClearCopybookCacheCommand.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/services/LanguageClientServiceTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/commands/ClearCopybookCacheCommand.ts
- clients/cobol-lsp-vscode-extension/src/constants.ts
- clients/cobol-lsp-vscode-extension/src/extension.ts
- clients/cobol-lsp-vscode-extension/src/services/util/FSUtils.ts
Provide command to clear downloaded copybook cache.
> feature: Provide command to clear downloaded copybook cache.

- clients/cobol-lsp-vscode-extension/syntaxes/COBOL.tmLanguage.json
Signed-off-by: niharikasw91 <niharikasw91@gmail.com>
> Update the comment area regular expression

- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
> fix: Fix failing build

- Jenkinsfile
Signed-off-by: niharikasw91 <niharikasw91@gmail.com>
> ci: experiment

- clients/cobol-lsp-vscode-extension/package.json
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CachingConfigurationService.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/utils/SettingsParametersEnum.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/CachingConfigurationServiceTest.java
Predefined section only for DaCo
> fix: Predefined section only for DaCo

- server/engine/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/IdmsParser.g4
- server/engine/src/test/java/org/eclipse/lsp/cobol/positive/FileBasedTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/idms/TestIdmsGetStatement.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/idms/TestIdmsSetStatement.java
> fix: Minor fix for IDMS grammar

- clients/cobol-lsp-vscode-extension/src/extension.ts
- clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookMessageHandler.ts
> fix: Enable copybook download

- server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookReferenceRepoImpl.java
> fix: Reanalyze copybook changes

- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/WatcherService.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/WatcherServiceImpl.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookNameServiceImpl.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/delegates/validations/CobolLanguageEngineFacade.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/WatcherServiceImplTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockTextDocumentService.java
Watch folders specified using fileBasenameNoExtension variable
> fix: Watch folders specified using fileBasenameNoExtension variable

- clients/cobol-lsp-vscode-extension/src/__tests__/services/copybook/CopybookMessageHandlerTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookMessageHandler.ts
> fix: Resolve downloaded copybooks

- server/engine/src/main/java/org/eclipse/lsp/cobol/domain/modules/ServiceModule.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolLanguageServer.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookIdentificationBasedOnExtension.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookIdentificationCombinedStrategy.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookIdentificationService.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookIdentificationServiceBasedOnContent.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookNameService.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/copybooks/CopybookNameServiceImpl.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/ClientServerTestModule.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/TestModule.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/CobolLanguageServerTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/copybooks/CopybookIdentificationBasedOnExtensionTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/copybooks/CopybookIdentificationServiceBasedOnContentTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockTextDocumentService.java
Change strategy for copybook identification
> fix: Change strategy for copybook identification

- server/engine/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/DaCoParser.g4
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/daco/TestDaCoTableRowModifyStatement.java
Update row modify DaCo grammar rule
> fix: Update row modify DaCo grammar rule

- clients/cobol-lsp-vscode-extension/package-lock.json
> fix: package-lock.json

- server/common/src/main/java/org/eclipse/lsp/cobol/common/model/NodeType.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/engine/CobolLanguageEngine.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/model/extendedapi/CFASTNodeType.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/model/tree/AtEndNode.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/visitor/CobolVisitor.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CFASTBuilderImpl.java
- server/engine/src/test/resources/cfast/case46.cbl
- server/engine/src/test/resources/cfast/case46.result.json
Support AT END for CFAST graph
> fix: Support AT END for CFAST graph

- clients/cobol-lsp-vscode-extension/package.json
- clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
Based on the first line of the source
> feat: Automatic Cobol Detection

- server/common/pom.xml
- server/dialect-daco/pom.xml
- server/dialect-idms/pom.xml
- server/engine/pom.xml
- server/pom.xml
> fix: Exclude DaCo from test coverage

- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
Fix lost changes after formatting document
> fix: Fix lost changes after formatting document

- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolLanguageServer.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolTextDocumentService.java
- server/engine/src/main/resources/META-INF/native-image/basic/reflect-config.json
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/CobolTextDocumentServiceTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/mocks/MockTextDocumentService.java
Add 'textDocument/diagnostic' support to LS
> feat: Add 'textDocument/diagnostic' support to LS

- clients/cobol-lsp-vscode-extension/src/__tests__/services/LanguageClientServiceTest.spec.ts
> test: fix failing tests

- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/engine/UseCaseInitializerService.java
support dialect discovery for positive tests
> test: support dialect discovery for positive tests

- server/engine/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolLexer.g4
- server/engine/src/main/antlr4/org/eclipse/lsp/cobol/core/parser/CobolParser.g4
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestEndIfDoesNotProduceError.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestFreeStatement.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestSetUpDownBy.java
Support free statements.
Ref -
https://www.ibm.com/docs/en/cobol-zos/6.3?topic=statements-free-statement
> feat: Support free statements

- server/engine/src/main/resources/META-INF/native-image/basic/reflect-config.json
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/CobolLanguageServerTest.java
update native build configuration
> fix: update native build configuration

- clients/cobol-lsp-vscode-extension/src/__tests__/commands/SmartTabCommandTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/commands/SmartTabCommand.ts
> feature: Add multi select smart tab.

- clients/cobol-lsp-vscode-extension/src/__tests__/commands/ClearCopybookCacheCommand.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/commands/ClearCopybookCacheCommand.ts
- clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookMessageHandler.ts
Fix copybook download and clear
> fix: Fix copybook download and clear

- CHANGELOG.md
- clients/cobol-lsp-vscode-extension/CHANGELOG.md
- clients/cobol-lsp-vscode-extension/src/__tests__/commands/ClearCopybookCacheCommand.spec.ts
- clients/cobol-lsp-vscode-extension/src/__tests__/extensionTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/commands/ClearCopybookCacheCommand.ts
- clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookMessageHandler.ts
Fix copybook download and clear
> Release v1.1.2

- clients/cobol-lsp-vscode-extension/src/services/copybook/CopybookMessageHandler.ts
resolve copybook extension at runtime
> fix: resolve copybook extension at runtime

- clients/cobol-lsp-vscode-extension/src/__tests__/commands/SmartTabCommandTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/commands/SmartTabCommand.ts
- clients/cobol-lsp-vscode-extension/src/extension.ts
preserve alignment while multiselect smart tab
> feat: preserve alignment while multiselect smart tab

- server/engine/src/main/java/org/eclipse/lsp/cobol/core/engine/dialects/WorkingFolderService.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/core/engine/dialects/WorkingFolderServiceTest.java
Discovery of dialects on windows
> fix: Discovery of dialects on windows

- .github/workflows/CI.yml
Changes to add dialect jar for 1.2.0 release
> ci: Changes to add dialect jar for 1.2.0 release

- server/common/src/main/java/org/eclipse/lsp/cobol/common/message/MessageService.java
- server/dialect-daco/src/main/resources/resourceBundles/messages_en.properties
- server/dialect-daco/src/test/resources/resourceBundles/messages_en.properties
- server/dialect-idms/src/main/resources/resourceBundles/messages_en.properties
- server/dialect-idms/src/test/resources/resourceBundles/messages_en.properties
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/engine/dialects/WorkingFolderService.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/messages/CobolLSPropertiesResourceBundle.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/messages/PropertiesMessageService.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolLanguageServer.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/CobolWorkspaceServiceImpl.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/settings/CachingConfigurationService.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/service/settings/ConfigHelper.java
- server/engine/src/main/resources/resourceBundles/messages_en.properties
- server/engine/src/test/java/org/eclipse/lsp/cobol/core/MessageServiceParserTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/core/messages/CobolLSPropertiesResourceBundleTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/core/messages/PropertiesMessageServiceTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/CobolLanguageServerTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/service/WorkspaceServiceTest.java
> refactor: split resources bundle

- .github/workflows/CI.yml
> chore: test mac-os native build on mac-os11

- .github/workflows/CI.yml
Co-authored-by: Aman Prashant <aman.prashant@broadcom.com>
> chore: fix build for macOS (#1739)

- clients/cobol-lsp-vscode-extension/src/__tests__/services/snippets/SnippetTest.spec.ts
- clients/cobol-lsp-vscode-extension/src/constants.ts
- clients/cobol-lsp-vscode-extension/src/services/Settings.ts
- clients/cobol-lsp-vscode-extension/src/services/snippetcompletion/SnippetCompletionProvider.ts
- clients/cobol-lsp-vscode-extension/src/services/snippetcompletion/dacoSnippets.json
- clients/cobol-lsp-vscode-extension/src/services/snippetcompletion/idmsSnippets.json
> revert: revert files related to snippets and dialect registry

- server/engine/src/test/java/org/eclipse/lsp/cobol/positive/PositiveTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/DialectConfigs.java
fix for failing external tests
> test: fix for failing external tests

- server/engine/src/main/resources/META-INF/native-image/basic/reflect-config.json
> fix: Add CCF reflection configuration for native build

- server/engine/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/replacement/ReplacementHelper.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/replacement/ReplacingServiceImpl.java
- server/engine/src/main/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/replacement/SearchPattern.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/core/preprocessor/delegates/util/impl/ReplacingServiceImplTest.java
- server/engine/src/test/java/org/eclipse/lsp/cobol/usecases/TestReplaceDirectiveWithDot.java
> fix: Fix replacement dot behaviour

- clients/idms-dialect-support/README.md
First draft of a readme for the new IDMS add-on
> IDMS readme first draft
